include/msg.h
it will allow to create and link objects with one message
=> include/msg: added parent oid to create message type

src/proc/process.c
exec after vfork resulted in destroyed environment of parent process
=> execve: do not destroy argv and envp syscall params

src/proc/process.c
illegal races spotted in syspage please send all units
=> proc: fix process state race when spawning syspage program

src/vm/map.c
=> vm: fix integer overflow

include/arch/ia32.h, src/hal/ia32/Makefile, src/hal/ia32/cpu.c, src/hal/ia32/pci.c, src/hal/ia32/pci.h
HO! HO! HO!
early Christmas present for Phoenix:
-pci code refactor
-cap list support
P.S.
But seriously merge it after the holidays
=> ia32: added support for pci capability list

toolchain/build-toolchain.sh
The libraries gmp, mpfr, mpc are built together with GCC [link](https://gcc.gnu.org/install/prerequisites.html) :
Alternatives [link](https://gcc.gnu.org/wiki/InstallingGCC) :
1. installation and use of system libraries.
2. after extracting the GCC source archive, simply run the ./contrib/download_prerequisites script in the GCC source directory.
Both do not provide version control.
=> New version of the build-toolchain.sh

include/arch/stm32l1.h, include/arch/stm32l4.h, src/Makefile.armv7, src/hal/armv7/Makefile, src/hal/armv7/console-stm32l1.c, src/hal/armv7/console-stm32l4.c, src/hal/armv7/interrupts-imxrt.c, src/hal/armv7/interrupts-stm32.c, src/hal/armv7/interrupts.h, src/hal/armv7/stm32.h, src/hal/armv7/stm32l1.c, src/hal/armv7/stm32l4.c
=> STM32L4 port

src/Makefile, src/hal/armv7/Makefile, src/hal/ia32/Makefile
Files:
```
src/hal/arm/Makefile
src/hal/armv7/Makefile
src/hal/armv7/_init-stm32.S
```
have line-endings CR+LF.
Is this correct?
=> Makefile: changed pipe 'grep | awk' to 'awk', unnecessary 'echo' removed

src/hal/ia32/pmap.c
The BDA (BIOS Data Area) and EBDA (Extended BIOS Data Area) should not be used by the OS, since these memory areas are used by BIOS/SMM.
=> Exclude BIOS SMM memory areas from usage

include/sysinfo.h, src/proc/threads.c
Make getting jiffies time consistent. This is needed by top utility.
=> ia32: Cleanup cpu time calculation

programs.c
Fixing incorect include path in programs.c
=> programs: Fix include

hal/riscv64/_interrupts.S, hal/riscv64/pmap.c, proc/process.c, proc/userintr.c, vm/map.c
Fixes required for phoenix on RISCV64 Qemu
=> Riscv64 fix pack

hal/arm/pmap.c, hal/arm/pmap.h, hal/armv7m/imxrt/10xx/imxrt10xx.c, hal/armv7m/imxrt/_init.S, hal/armv7m/imxrt/pmap.c, hal/armv7m/imxrt/pmap.h, hal/armv7m/imxrt/syspage.c, hal/armv7m/imxrt/syspage.h, hal/armv7m/stm32/pmap.c, hal/armv7m/stm32/pmap.h, hal/armv7m/stm32/syspage.h, hal/ia32/pmap.c, hal/ia32/pmap.h, hal/riscv64/pmap.c, hal/riscv64/pmap.h, main.c, vm/map.c, vm/page-nommu.c
Changes include in this PR have been tested on imxrt, stm32, ia32 and riscv64.
=> vm: multimaps initialization based on data from syspage.

include/syscalls.h, proc/process.c, proc/process.h, syscalls.c
This PR is associated with other in libphoenix repository.
=> process: launch process from syspage

hal/arm/console-imx6ull.c, hal/ia32/console-serial.c
`NULL` is used to test pointer not null character.
=> changed test for null character

hal/armv7a/_hal.S, hal/armv7a/_interrupts.S, hal/armv7a/imx6ull/interrupts.c, hal/armv7a/interrupts.h, hal/armv7a/zynq7000/Makefile, hal/armv7a/zynq7000/_init.S, hal/armv7a/zynq7000/console.c, hal/armv7a/zynq7000/interrupts.c, hal/armv7a/zynq7000/pmap.c, hal/armv7a/zynq7000/pmap.h, hal/armv7a/zynq7000/syspage.c, hal/armv7a/zynq7000/syspage.h, hal/armv7a/zynq7000/timer.c, hal/armv7a/zynq7000/zynq.c
The following components are under development:
- _hal.S, 
- _interrupts.S,
- gic,
- timer,
- pmap,
- syspage.
=> initialization of Zynq-7000

hal/armv7a/zynq7000/syspage.h, hal/armv7m/imxrt/pmap.c, hal/armv7m/imxrt/syspage.h
This PR is associated with [syspage changes in plo.](https://github.com/phoenix-rtos/plo/pull/44)
=> change types in syspage

proc/process.c
=> proc: output more info about exceptions

Makefile
=> Makefile: get HEAD revision using shell invocation

syscalls.c
libphoenix change as a part of this PR: https://github.com/phoenix-rtos/libphoenix/pull/88
JIRA: RTOS-27
=> syscalls: const-ify debug() param

include/posix.h, posix/posix.c
=> posix: add packet sockets

hal/armv7m/imxrt/syspage.h
This PR depends on changes in [plo](https://github.com/phoenix-rtos/plo/pull/94)
Change has been tested on imxrt106x.
=> armv7m-imxrt/syspage: change program's name size

hal/armv7m/imxrt/10xx/imxrt10xx.c, hal/armv7m/imxrt/117x/imxrt117x.c
JIRA: PD-131
While interrupt is cleared, it shouldn't be done using logical OR operation. It causes that several other interrupts might be cleared as well.
https://developer.arm.com/documentation/dui0646/c/cortex-m7-peripherals/nested-vectored-interrupt-controller/interrupt-clear-enable-registers?lang=en
=> armv7m/imxrt: fix setting interrupts

include/msg.h
JIRA: DTR-75
Needed for `realpath()` optimizations. Actual changes to be done in `libphoenix` and relevant filesystems
=> msg: allow getattr/setattr to return error

hal/armv7m/imxrt/117x/imxrt117x.c, hal/armv7m/imxrt/117x/imxrt117x.h
Removed duplicated code
Inline functions (dmb, dsb and isb asm instructions) were duplicated, cpu.h implements these already
Code duplication is bad.
=> imxrt117x: Use hal functions for asm inline

include/posix.h, posix/posix.c
JIRA: DTR-6
Required for IP driver. Note that currently LWIP ignores "domain" parameter in "socket" call so it will attempt to open AF_INET socket instead (the same applies to AF_PACKET sockets). I will fix it later in IPSEC driver commit.
=> posix: add key management sockets

posix/posix.c
=> posix: init hostname, remove pointless hostname checks

proc/process.c
It could happen that process->mapp != NULL and process->pmapp == NULL
which resulted in exception in scheduler (pmap_switch(NULL)).
JIRA: RTOS-69
=> vfork/fork: fix insufficient locking

proc/threads.c
Protect stack canary initialization with spinlock.
Fixes [phoenix-rtos/phoenix-rtos-project#130](https://github.com/phoenix-rtos/phoenix-rtos-project/issues/130)
[JIRA: RTOS-73](https://jira.phoenix-rtos.com/browse/RTOS-73)
=> proc/threads.c: fix stack canary initialization

hal/armv7m/stm32/l4/timer.c
Previous method always did two addtional reads on timer fetch fail
JIRA: RTOS-79
Improved timer cnt fetch routine
=> stm32l4/timer: Improved getting timer value

main.c, proc/process.c, proc/threads.c
Few patches that fixes various problems in kernel. It seems that undefined behaviour (taking address of packed struct member) was cause of crash when using sysexec command.
We needed to fix the crash when using sysexec.
=> Fixed crash on imxrt117x

hal/armv7a/imx6ull/imx6ull.c
=> imx6ull: kick watchdog power down counter

proc/process.c
DONE: RTOS-93
Provide log if bad relocation is found and skipped
So the developer will know, if his ELF gives bad direction for kernel
=> proc/nommu: Show log if bad relocations are found

hal/armv7a/cpu.h, hal/armv7a/imx6ull/_init.S, hal/armv7a/imx6ull/imx6ull.c, hal/armv7a/zynq7000/zynq.c
Add `wdgreload` syscall for imx6ull platform. Enable a watchdog timer in plugin.
PR requires changes in the psu scripts, so I will merge it by myself.
=> imx6ull: watchdog handling

hal/ia32/cpu.c, syscalls.c
-syscalls: fixes to prevent exceptions in syscalls_signalPost
-hal: ia32: apply clang-format to cpu.c file
-hal: ia32: fix calling hal_cpuReschedule with NULL arguments
Killing processes in using psh command returned exceptions. These changes solve problems with kill.
=> fixes for psh kill working

hal/ia32/cpu.c, include/arch/ia32.h
=> ia32: add platformctl reboot

hal/armv7a/imx6ull/console.c, hal/armv7a/zynq7000/console.c, hal/armv7m/imxrt/10xx/console.c, hal/armv7m/imxrt/117x/console.c, hal/armv7m/stm32/l4/console.c, hal/console.h, lib/printf.c
Kernel logs are presented in the same way on each platform.
Changes applied to `armv7m` and `armv7a`.
=> hal: unified colors in console

hal/armv7a/imx6ull/console.c, hal/armv7a/zynq7000/console.c, hal/armv7a/zynq7000/interrupts.c, hal/armv7m/cpu.c, hal/armv7m/imxrt/10xx/config.h, hal/armv7m/imxrt/10xx/console.c, hal/armv7m/imxrt/117x/config.h, hal/armv7m/imxrt/117x/console.c, hal/armv7m/stm32/config.h, hal/armv7m/stm32/l4/console.c
- fix console
- update cpu info & features for Cortex-M
=> hal: update cpu info & features

hal/armv7a/exceptions.c, hal/armv7a/string.c, hal/armv7m/exceptions.c, hal/armv7m/stm32/config.h, hal/armv7m/string.c, hal/string.h
=> hal/string.h: change declaration of hal_memcpy, hal_memset and add hal_i2s

hal/armv7a/string.c, hal/armv7m/string.c, hal/string.h
=> hal/string: don't return pointer form hal_memset and hal_memcpy

hal/armv7a/imx6ull/_init.S, hal/armv7a/imx6ull/imx6ull.c
=> armv7a/imx6ull: persistent bits clearing in init with bootreason update

Makefile, klog/Makefile, klog/klog.c, klog/klog.h, lib/printf.c, main.c
=> klog: Add kernel log buffer

klog/klog.c
=> klog: Fix warnings

hal/ia32/_interrupts.S, hal/ia32/console-serial.c, hal/ia32/console.c, hal/ia32/cpu.c, hal/ia32/exceptions.c, hal/ia32/hal.c, hal/ia32/halsyspage.h, hal/ia32/interrupts.c, hal/ia32/pmap.c, include/arch/syspage-imxrt.h, include/syspage.h, syspage.h
- fix initialization of `_interrupts_multilock` variable
- apply new syspage approach
- update console
**NOTE:** console-vga doesn't work correctly. `lib_printf()` sets console color using ASCI what is incomprehensible to vga.
Changes will be introduced in a separate PR.
Furthermore, **console-serial** has hard-coded instance of base address. This code will be changed in the next PR as well.
=> hal/ia32: apply new syspage

Makefile, hal/armv7a/imx6ull/_init.S, hal/armv7a/imx6ull/imx6ull.c, klog/Makefile, klog/klog.c, klog/klog.h, lib/printf.c, main.c, posix/posix.c, proc/msg.c, proc/process.c
- merge master into feature/syspage
- apply new hal interface to klog
RTOS-139
=> merge master into feature/syspage

posix/sockdefs.h, posix/unix.c
=> posix/unix: add support for custom SOCK_LARGEBUF flag

hal/ia32/console.c
=> hal/ia32/console-vga: change colors using ANSI escape sequences

syspage.c
=> syspage: fix map's name relocation

posix/posix.c
Add new attribute types which allow to retrieve number of allocated 512-byte blocks and optimal I/O size access for a given file.
[JIRA: DTR-205](https://jira.phoenix-rtos.com/browse/DTR-205)
https://github.com/phoenix-rtos/libphoenix/pull/156
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/56
=> posix/fstat: add 'atBlocks' and 'atIOBlock' attributes for setting stat.st_blocks and stat.st_blksize fields

posix/unix.c
- set peer socket to disconnected state
- send on disconnected socket returns EPIPE (SOCK_STREAM, SOCK_SEQPACKET)
- send on disconnected socket return ECONNREFUSED (SOCK_DGRAM)
- send on disconnected socket sends SIGPIPE (SOCK_STREAM, SOCKSEQPACKET)
- recv on disconnected sockets returns 0 (SOCK_STREAM, SOCK_SEQPACKET)
JIRA: DTR-241
Required for openiked. Currently send/recv on socket connected to closed socket will crash kernel.
=> posix/unix: handle correctly removal of connected socket

posix/posix.c, posix/posix_private.h, posix/unix.c
=> posix/unix: add unix sockets polling

hal/armv7a/imx6ull/timer.c, include/posix.h, posix/posix.c, posix/posix_private.h, posix/unix.c
=> imx6ull: fix timer & merge master 

hal/armv7a/imx6ull/_init.S
=> imx6ull/_init: restore plugin and controllers initialization

include/syscalls.h, posix/posix.c, posix/posix.h, syscalls.c
[JIRA: DTR-250](https://jira.phoenix-rtos.com/browse/DTR-250)
https://github.com/phoenix-rtos/libphoenix/pull/165
=> posix: add fsync syscall

proc/threads.c
[JIRA: RTOS-153](https://jira.phoenix-rtos.com/browse/RTOS-153)
=> proc: fix setting kernel stack for kernel threads in threads_schedule()

hal/armv7a/Makefile, hal/armv7a/_memtest.S, hal/armv7a/memtest.c
=> imx6ull: add short ddr test

hal/armv7m/arch/cpu.h
Fixes phoenix-rtos/phoenix-rtos-project#295
[JIRA: PD-239](https://jira.phoenix-rtos.com/browse/PD-239)
=> hal/armv7m/cpu.h: increase SIZE_KSTACK to 4 pages

include/posix.h, include/syscalls.h, posix/posix.c, posix/posix.h, syscalls.c
=> posix: implement sys_futimes() (previously sys_utimes())

include/posix.h, include/syscalls.h, posix/posix.c, posix/posix.h, syscalls.c
=> posix: remove obsolete sys_utimes() syscall

proc/lock.h, proc/threads.c, proc/threads.h, syscalls.c
Added locks priority inheritance. Fixes priority inversion issue.
[JIRA: DTR-269](https://jira.phoenix-rtos.com/browse/DTR-269)
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/90
=> proc: add locks priority inheritance

proc/threads.c
Removed adding newly created thread twice to the `threads_common.id` tree.
New thread is added in `thread_alloc()`.
[JIRA: RTOS-161](https://jira.phoenix-rtos.com/browse/RTOS-161)
=> proc: fix adding newly created thread to threads_common.id tree

lib/printf.c
=> lib/printf: Fix setting console color

hal/armv7m/stm32/l4/stm32l4.c, include/arch/stm32l4.h
JIRA: ISC-172
Fix wrong registers read/write and add missing defines
Read reboot reason is needed for catching issues
=> stm32/l4: Fix reboot reason flags handling

hal/armv7m/stm32/l4/timer.c
=> stm32l4: Timer rewrite - don't mask/unmask interrupts

proc/threads.c
Thread which holds locks can lower its priority (up to the highest priority of the threads waiting for any of the locks it took).
[JIRA: DTR-281](https://jira.phoenix-rtos.com/browse/DTR-281)
=> proc: fix condition for lowering thread priority in proc_threadPriority()

proc/threads.c
=> proc: proc_threadPriority(-1) fix (implicit integer promotion)

hal/armv7m/stm32/l4/stm32l4.c
=> stm32l4: Removed sev, wfe stale errata workaround

hal/armv7a/zynq7000/console.c, hal/armv7a/zynq7000/zynq.c, hal/armv7a/zynq7000/zynq.h
=> zynq7000/console: Use UART pin definitions from board_config.h

hal/armv7a/imx6ull/console.c, hal/armv7m/stm32/l1/console.c, hal/armv7m/stm32/l4/console.c, hal/ia32/console.c
=> hal/console: Remove console clear, add console clear on VGA

hal/armv7m/stm32/l4/stm32l4.c
=> stm32l4: Fix bad SCB FPU control registers offsets

include/signal.h, proc/threads.c, proc/threads.h
JIRA: RTOS-236
implements signal to kill one thread
JIRA: RTOS-236 - needed for pthread_cancel implementation
=> implement signal to kill one thread

hal/armv7a/cpu.c, hal/armv7m/cpu.c, hal/armv7m/imxrt/10xx/imxrt10xx.h, hal/armv7m/imxrt/117x/imxrt117x.h, hal/cpu.h, hal/ia32/cpu.c, hal/riscv64/cpu.c, main.c, proc/process.c, proc/process.h, syscalls.c, test/proc.c, vm/map.c, vm/map.h
JIRA: RTOS-267
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/536
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/158
https://github.com/phoenix-rtos/plo/pull/215
https://github.com/phoenix-rtos/libphoenix/pull/210
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/348
=> NOMMU: Add option to exec ELF from different map than file's

hal/armv7a/arch/cpu.h, hal/armv7m/arch/cpu.h, hal/cpu.h, hal/ia32/arch/cpu.h, hal/riscv64/arch/cpu.h, proc/process.h, proc/threads.c
Some of the code is no longer used and make the thread scheduling function ambiguous.
The clean up is needed to make a correct documentation of scheduling policy in Phoenix-RTOS.
=> hal & proc: remove dead code

log/log.c
klog is added to all architectures
RTOS-142
=> log: remove KLOG_ENABLE define

Makefile, log/log.c, log/log.h, main.c, usrv.c, usrv.h
more details:
- user server receive msg on port 0
- modify log to be a part of user server
RTOS-298
=> add user server

hal/armv7a/zynq7000/console.c
RTOS-142
Define name has been changed in `board_config` for all zynq7000 projects.
=> zynq7000/console: update UART_CONSOLE define

proc/process.c
Solving issue: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/496
RTOS-304
Custom stack can be used on MMU targets:
`LOCAL_LDFLAGS := -z stack-size=0x2000 -z noexecstack`
=> process: use PT_GNU_STACK elf section size on MMU targets

vm/kmalloc.c
DONE: RTOS-350
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/597
=> kmalloc: Fix out of memory not being handled

hal/armv7a/zynq7000/timer.c
=> zynq7000: Increase system timer resolution

posix/posix.c, proc/process.c, proc/threads.c
Fixes: phoenix-rtos/phoenix-rtos-project#600
DONE: RTOS-379
=> kernel: Fix wrong value of child's process group

posix/posix.c
DONE: RTOS-381
Fix processes having non-existing parent
=> posix: Attach children to init after parent death

posix/unix.c
Allows setting SO_RCVBUF on sockets created by socketpair(). Data from old buffer is not copied to new buffer.
DONE: BES-239
=> posix/unix: support socket receive buffer reallocation

syscalls.c
JIRA: RTOS-384
Fixes the returned name of `syspage` program to be `argv[0]` instead of unparsed `argv` cmdline string.
Unparsed cmdline (argv) special markers:
`\0` - end of C string
`X`  - means execute program (if it occurs, strip from program name)
`;`   - separator of arguments (strip from the first to the end of string)
Cases:
* `progname1`
* `Xprogname2;arg1;arg2;arg3`
* `progname3;arg1;arg2`
After applying this fix will be:
* `progname1`
* `progname2`
* `progname3`
Function is used in dummyfs (https://github.com/phoenix-rtos/phoenix-rtos-filesystems/blob/master/dummyfs/srv.c#L48-L53) to "mount" syspage resources.
Without the proposed change `ls /syspage` is failing:
=> syscalls: Fix syspageprog() to return prog name

proc/threads.c
=> tls: Fix uninitialized variable

hal/armv7a/imx6ull/Makefile, hal/armv7a/imx6ull/_init.S
JIRA: RTOS-398
Adds support for boot form plo.
imx6ull lacks support for starting from flash
=> imx6ull: boot from plo

log/log.c
=> klog: bugfixes, log_write and fifo rewrite

hal/ia32/cpu.c
Now the '`nx'` feature is not shown for a processor that has it.
The variable `eax` of the `cpu_feature_t` structure is of type `u32`, and is never less  than `0`.
Changes:
1. Change variable `eax` to type `int`.
If the `eax` variable is to remain of type `u32`, then you need to cast the variable `eax` to `int` type .
2. Removed the `overflow` variable. If the buffer size is too small then exit the `for` loop.
3. The `'+'` char is added to the second and subsequent features.
ia32-generic
=> ia32: hal_cpuFeatures() fixed the 'nx' feature check

log/log.c
=> klog: Allow EPIPE on blocked reader

proc/process.c, syscalls.c
DONE: RTOS-435
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/683
=> NOMMU: Return -ENOSYS on fork() call

log/log.c, posix/posix.c, posix/unix.c, proc/lock.h, proc/mutex.c, proc/name.c, proc/ports.c, proc/process.c, proc/threads.c, test/vm.c, vm/amap.c, vm/kmalloc.c, vm/map.c, vm/object.c, vm/page-nommu.c, vm/page.c
DONE: RTOS-431
Add names to locks to assist in profiling and debugging of locks
=> lock: Add human-readable locks names

vm/object.c
=> vm/object: Fix deadlock in vm_objectGet

Makefile
Quickfix for incremental build to work until better makefiles would be introduced. Please note that version string might still be invalid.
JIRA: CI-30
=> makes: include deps for incremental build to work

hal/ia32/string.c, hal/riscv64/string.c
=> string: fix lack of unsigned char convert in strcmp, strncmp

hal/armv7m/imxrt/_init.S, hal/armv7m/stm32/_init.S, hal/armv7m/stm32/l4/stm32l4.c
Fix erratum 2.3.1 and 2.2.4
JIRA: RTOS-470
=> stm32l4: Errata fixes

hal/armv7m/stm32/l4/timer.c, hal/ia32/_interrupts.S, hal/ia32/interrupts.c, proc/threads.c
=> STM32L4 low power timer fixes

hal/sparcv8leon3/_init.S, hal/sparcv8leon3/_interrupts.S, hal/sparcv8leon3/_traps.S, hal/sparcv8leon3/arch/cpu.h, hal/sparcv8leon3/arch/exceptions.h, hal/sparcv8leon3/cpu.c, hal/sparcv8leon3/exceptions.c, hal/sparcv8leon3/gr716/console.c, hal/sparcv8leon3/gr716/gr716.c, hal/sparcv8leon3/gr716/gr716.h, hal/sparcv8leon3/gr716/timer.c, hal/sparcv8leon3/spinlock.c, include/arch/gr716.h
- Add full support for register windows.
- Switch to kstack when entering kernel.
JIRA: RTOS-406, RTOS-417
=> Leon3: use register windows in kernel

hal/armv7a/exceptions.c, hal/armv7a/imx6ull/imx6ull.c, hal/armv7a/zynq7000/zynq.c, hal/armv7m/cpu.c, hal/armv7m/exceptions.c, hal/cpu.h, hal/ia32/exceptions.c, hal/riscv64/cpu.c, hal/riscv64/exceptions.c, hal/sparcv8leon3/cpu.c, hal/sparcv8leon3/exceptions.c
=> Always reboot after non-recoverable exception if not DEBUG

hal/armv7m/arch/cpu.h, hal/armv7m/stm32/interrupts.c, hal/armv7m/stm32/stm32.h, proc/process.c, proc/userintr.c, syscalls.c
Recent changes in phoenix-rtos-build introduced a global define of the form `__CPU_*` based on `TARGET_SUBFAMILY` and `__TARGET_*` based on `TARGET_FAMILY`, this commit adapts the kernel to these changes.
Not verified with `STM32L152xx` targets.
JIRA: RTOS-519
=> Adjust CPU to changes in phoenix-rtos-build

hal/sparcv8leon3/cpu.c, hal/sparcv8leon3/gr716/gr716.c, include/arch/gr716.h
=> hal/sparcv8leon3: implement cpu reboot

hal/sparcv8leon3/interrupts.c
=> sparcv8leon3: add extended interrupts handling

lib/Makefile, lib/assert.c, lib/assert.h, lib/lib.h, lib/list.c, lib/list.h, lib/printf.c, lib/printf.h, proc/threads.c
Implementation of asserts + some use cases of these
To aid in code quality control and ease debugging
=> Kernel asserts implementation

include/errno.h, proc/threads.c
=> proc_join: add deadlock checking

proc/elf.h, proc/process.c
=> Add address checking in process_load

proc/process.c
JIRA: RTOS-560
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/798
=> process_load: fix 64-bit elf validation

proc/process.c
JIRA: RTOS-555
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/141
=> process: Fix warning

syscalls.c
=> Apply MISRA to syscalls.c

proc/threads.c
=> threads: reduce number of locks of threads_common.spinlock

vm/map.c
DONE: RTOS-551
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/721
=> NOMMU/vm_mapDestroy: Remove only entries associated with the map

hal/armv7a/Makefile, hal/armv7a/imx6ull/Makefile, hal/armv7a/zynq7000/Makefile, hal/armv7m/Makefile, hal/armv7m/imxrt/10xx/Makefile, hal/armv7m/imxrt/117x/Makefile, hal/armv7m/imxrt/Makefile, hal/armv7m/stm32/Makefile, hal/armv7m/stm32/l1/Makefile, hal/armv7m/stm32/l4/Makefile, lib/Makefile, log/Makefile, test/Makefile, vm/Makefile
=> Fix makefile description headers

README.md
- remove STM32L1 for now,
- add sparcv8leon3-gr716.
DONE: RTOS-573
=> Update supported targets list

Makefile
=> Bump version to 3.0

syspage.c
=> syspage_progShow: Remove backspace print

hal/sparcv8leon3/cpu.c
=> sparcv8leon3/reboot: remove unnecessary register setting

hal/armv7a/cpu.c, proc/process.c
=> Refactor parentkstack handling

Makefile
JIRA: CI-344
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/834
=> make: switch to linking by gcc

hal/sparcv8leon3/gr716/gr716.h
=> gr716: use SYSCLK_FREQ defined in board_config

proc/msg-nommu.c
=> msg-nommu: Fix rid being allocaded in the wrong place

hal/riscv64/_interrupts.S, hal/riscv64/arch/spinlock.h, hal/riscv64/pmap.c, hal/riscv64/spinlock.c, proc/threads.c
There were bugs in spinlocks and pmap that caused crash provoked by latest changes (SMP fixes)
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/853
=> RISCV64: Fix bugs revealed after latest changes

hal/riscv64/arch/cpu.h
DONE: RTOS-623
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/856
=> riscv: Increase SIZE_KSTACK

posix/posix.c
- reap all init zombies (fix memory leak),
- consume SIGCHLD when parent is waiting in waitpid,
- reap orphan's zombies (fix memory leak).
DONE:  RTOS-624
Example code to showcase a memory leak that has been fixed:
```
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
void process(int level)
{
while (fork()) {
printf("level: %d\n", level);
if (!--level) {
break;
}
}
}
int main(int argc, char *argv[])
{
process(5000);
return 0;
}
```
Fixes a memory leak.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/188 (hopefully)
=> posix: posix_died rewrite

posix/posix.c
JIRA: RTOS-635
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/870
=> posix: fix exit codes connected with pinfo_find

hal/armv7m/imxrt/117x/imxrt117x.c
This change implements system `watchdog on imxrt117x` targets. For this purpose `WDOG3 is used`. WDOG1, WDOG2 and WDOG4 are set not to be used (disabled). Both `WDOG3` and WDOG4 are `allowed to be later reconfigured without cpu reset`. WDOG3 (system watchdog) as clock source will `use 32kHz RC oscillator` (LPO) and will `not use windowing`.
JIRA: RTOS-657
=> hal/imxrt117x: implement watchdog

lib/assert.c
Applies `NDEBUG` logic [consistent with that in exceptions handling function](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/master/hal/armv7m/exceptions.c#L100-L107) to `lib_assertPanic()`, if it occurs, depending on `NDEBUG` is defined or not the system will reset or halt. This change affects the operation of the `LIB_ASSERT_ALWAYS()` macro, but is neutral for regular `LIB_ASSERT()` which is `no-op` when `NDEBUG` is defined.
JIRA: RTOS-658
=> Apply NDEBUG logic in lib_assertPanic()

hal/armv7a/arch/cpu.h, hal/armv7a/cpu.c, hal/armv7m/arch/cpu.h, hal/armv7m/cpu.c, hal/armv8m/arch/cpu.h, hal/armv8m/cpu.c, hal/cpu.h, hal/ia32/Makefile, hal/ia32/_init.S, hal/ia32/_interrupts.S, hal/ia32/arch/cpu.h, hal/ia32/arch/interrupts.h, hal/ia32/arch/pmap.h, hal/ia32/cpu.c, hal/ia32/hal.c, hal/ia32/init.c, hal/ia32/init.h, hal/ia32/interrupts.c, hal/ia32/pmap.c, hal/ia32/timer.c, hal/ia32/tlb.c, hal/ia32/tlb.h, hal/riscv64/arch/cpu.h, hal/riscv64/cpu.c, hal/sparcv8leon3/arch/cpu.h, hal/sparcv8leon3/cpu.c, include/arch/syspage-ia32.h, proc/threads.c
Add interrupt balancing, I/O APIC and basic ACPI support.
Without this change, all of hardware interrupts go only to the first CPU. After this change they are handled by all of them (round robin).
=> hal/ia32: Add interrupt balancing

syscalls.c
=> syscalls: change return type of singalHandle and munmap to int

proc/threads.c
=> proc: Handle usleep(0) (yield)

hal/sparcv8leon3/_traps.S, hal/sparcv8leon3/arch/exceptions.h, hal/sparcv8leon3/exceptions.c
JIRA: RTOS-615
- Fix exceptions number calculation
- Fix page fault handling
=> hal/sparcv8leon3: fix exception handling

.codespell_ignore
=> codespell: ignore mapp and pmapp

include/syscalls.h, include/sysinfo.h, proc/msg.c, syscalls.c, vm/map.c, vm/map.h
=> mprotect: add syscall

posix/posix.c
=> posix_mkfifo: Return valid error

hal/armv7a/imx6ull/timer.c, hal/armv7a/zynq7000/timer.c, hal/armv7m/imxrt/timer.c, hal/armv7m/stm32/l1/timer.c, hal/armv7m/stm32/l4/timer.c, hal/armv8m/nrf/91/timer.c, hal/ia32/timer.c, hal/riscv64/timer.c, hal/sparcv8leon3/gaisler/timer.c, hal/timer.h, main.c
Make timers more modular and add displaying description string about them.
=> hal/ia32: Refactor timers

hal/sparcv8leon3/string.c
=> sparcv8leon3: fix hal_strncpy implementation

posix/posix.c
=> posix: Pass oid in msg in posix_fsync

hal/sparcv8leon3/gaisler/Makefile, hal/sparcv8leon3/gaisler/ambapp.c, hal/sparcv8leon3/gaisler/ambapp.h, hal/sparcv8leon3/gaisler/gr712rc/gr712rc.c, hal/sparcv8leon3/gaisler/gr712rc/gr712rc.h, hal/sparcv8leon3/gaisler/gr716/gr716.c, hal/sparcv8leon3/gaisler/gr716/gr716.h, hal/sparcv8leon3/sparcv8leon3.h, include/arch/gr712rc.h, include/arch/gr716.h, include/arch/sparcv8leon3.h
JIRA: RTOS-704
GRLIB components feature Plug and Play information about cores (e.g. address, interrupt number) stored in read-only memory. This PR adds support to read the information about given core through platformctl syscall.
Decided to use MMU bypass to make this feature work seamlessly on both MMU and NOMMU architectures.
=> sparcv8leon3: add amba pnp support

hal/armv7a/imx6ull/Makefile
- hal: imx6ull memtest: update to linking by gcc
*It's updated in the same way as it was done in https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/4e12696a61eddf207cf70ba6dcdeea69c9b8e5d4/Makefile#L55C1-L55C1 
It needs an update.
JIRA: RTOS-707
=> hal: imx6ull memtest: update to linking by gcc

syscalls.c
=> syscalls/mmap: Mask-out user space mmap flags

hal/armv7m/cpu.c, hal/armv7m/imxrt/10xx/imxrt10xx.c, hal/armv7m/imxrt/10xx/imxrt10xx.h, hal/armv7m/imxrt/117x/imxrt117x.c, hal/armv7m/imxrt/117x/imxrt117x.h, include/arch/imxrt.h, include/arch/imxrt1170.h
=> imxrt117x: Add cache management to platformctl

include/msg.h, lib/idtree.c, lib/idtree.h, lib/lib.h, posix/fdpass.c, posix/posix.c, posix/unix.c, proc/cond.c, proc/cond.h, proc/msg-nommu.c, proc/msg.c, proc/mutex.c, proc/mutex.h, proc/ports.c, proc/ports.h, proc/process.c, proc/process.h, proc/resource.c, proc/resource.h, proc/threads.c, proc/threads.h, proc/userintr.c, proc/userintr.h, syscalls.c
Replace multiple implementations of interval tree for ID allocations with one universal one.
=> Use idtree

lib/lib.h, proc/resource.c
=> proc/resource: Restore atomic decrement on resource_put()

proc/threads.c, proc/userintr.c
=> userintr: call broadcast instead of wakeup on cond

hal/sparcv8leon3/gaisler/console.c
JIRA: RTOS-719
Fix junk on `gr716-mimas` being written to console:
Before:
After:
=> gaisler/console: clear buffer before initialization

hal/armv7a/arch/cpu.h, hal/armv7m/arch/cpu.h, hal/armv8m/arch/cpu.h, hal/cpu.h
JIRA: RTOS-725
Not used and not generic API as u32 is only valid fo 32bit architectures
=> hal: remove cpuGetPC

hal/armv7m/imxrt/117x/imxrt117x.c
to allow faster access times
DONE: RTOS-723
=> imxrt117x: Change GPT1 mux to SYS_PLL3_DIV2

hal/armv8m/arch/cpu.h, hal/armv8m/cpu.c, hal/armv8m/hal.c, hal/armv8m/nrf/_init.S
- hal: armv8m: add hal_lockScheduler() stub
- hal: armv8m: rework signal handling
Added the newest changes needed in kernel for hal/armv8
=> nrf9160 port update

hal/sparcv8leon3/_interrupts-nommu.S, hal/sparcv8leon3/_interrupts.S, hal/sparcv8leon3/_traps.S, hal/sparcv8leon3/arch/cpu.h, hal/sparcv8leon3/exceptions.c
- add lazy FPU context stacking in interrupts
- handle FP disabled trap (taken when FP instruction is executed when FPU is disabled) that enables the FPU if it's present
NOTE: GRFPU hardware does not support denormalized numbers and will generate FP exception when encountered: https://www.gaisler.com/doc/antn/GRLIB-AN-0007.pdf
=> sparcv8leon3: use FPU

.codespell_ignore, hal/armv7m/stm32/l4/stm32l4.c, include/arch/stm32l4.h
JIRA: RTOS-733
Needed for https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/456
=> stm32l4x6: Add HSI48 control to platformctl

hal/armv7a/imx6ull/interrupts.c, hal/armv7a/spinlock.c, hal/armv7a/zynq7000/interrupts.c, hal/armv7m/imxrt/interrupts.c, hal/armv7m/spinlock.c, hal/armv7m/stm32/interrupts.c, hal/armv8m/nrf/interrupts.c, hal/armv8m/spinlock.c, hal/ia32/interrupts.c, hal/ia32/spinlock.c, hal/list.h, hal/riscv64/interrupts.c, hal/riscv64/spinlock.c, hal/sparcv8leon3/gaisler/irqamp.c, hal/sparcv8leon3/gaisler/irqmp.c, hal/sparcv8leon3/spinlock.c
=> hal: create list interface

hal/armv7m/imxrt/117x/imxrt117x.c
=> imxrt117x: fix SRC registers

hal/armv7m/imxrt/10xx/console.c, hal/armv7m/imxrt/117x/console.c
When working on imxrt1176-evk I noticed missing initial line during early console
`Phoenix-RTOS microkernel v. 3.0 rev: HASH`
This change fixes that.
before:
after:
JIRA: RTOS-749
=> imxrt: use board_config.h in early console

vm/map.c
Fix memory leak (last entry not being removed)
DONE: RTOS-753
=> map: Rewrite mapDestroy for NOMMU

Makefile, hal/Makefile, hal/armv7a/_armv7a.S, hal/armv7a/arch/cpu.h, hal/armv7a/cpu.c, hal/armv7m/arch/cpu.h, hal/armv7m/cpu.c, hal/armv7m/imxrt/_init.S, hal/armv7m/stm32/_init.S, hal/armv8m/arch/cpu.h, hal/armv8m/cpu.c, hal/armv8m/nrf/_init.S, hal/common.c, hal/cpu.h, hal/ia32/arch/cpu.h, hal/ia32/cpu.c, hal/riscv64/_interrupts.S, hal/riscv64/arch/cpu.h, hal/riscv64/cpu.c, hal/sparcv8leon3/_traps.S, hal/sparcv8leon3/arch/cpu.h, hal/sparcv8leon3/cpu.c, proc/process.c, proc/threads.c
Change semantics of last argument. And fix stack alignment
JIRA: RTOS-720
https://github.com/phoenix-rtos/libphoenix/pull/327
=> process: align stack at process start

hal/armv7m/imxrt/117x/imxrt117x.c, include/arch/imxrt1170.h
=> imxrt117x: add slice reset to platformctl

proc/process.c
=> process/load: Pass argv and envp as pointers to NULL instead of NULLs if empty

Makefile
=> Bump version to 3.1.0

hal/riscv64/cpu.c, hal/riscv64/hal.c, hal/riscv64/sbi.c, hal/riscv64/sbi.h, include/arch/riscv64.h
=> riscv64: add system reset handling

hal/armv8m/nrf/91/nrf91.c, include/arch/armv8m/nrf/91/nrf9160.h
Finalizing the nrf9160 basic port
=> hal: armv8m: add reboot platformctl for nrf91

hal/armv7m/stm32/l4/stm32l4.c
hal: fix return value for pctl_reboot get on stm32l4
before:
```
(psh)% reboot -g
(psh)%
```
after (example output):
```
(psh)% reboot -g
0x00000004
(psh)%
```
=> hal: fix return value for pctl_reboot get on stm32l4

lib/strtoul.c, lib/strtoul.h
=> lib_strtoul: Fix endptr check

include/events.h, include/file.h, posix/posix.c
Remove leftover duplicate libphoenix definitions.
=> include: add events.h and file.h headers

include/posix-types.h
JIRA: RTOS-793
:upside_down_face:
=> include/posix-types.h: remove unnecessary include

hal/armv7m/_memcpy.S, hal/armv8m/_memcpy.S
JIRA: RTOS-789
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/526#issuecomment-1988237346
=> arm/memcpy: optimize register usage

include/arch/ia32/syspage.h
Required to handle ECAM access for PCIe
JIRA: RTOS-800
=> ia32/syspage: add ACPI MCFG table pointer

hal/ia32/arch/cpu.h, proc/process.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1012
=> Fix occasional triple-faults on ia32

include/syscalls.h, proc/process.h, syscalls.c, vm/map.c, vm/map.h
JIRA: RTOS-808
ABI breaking change
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/977
=> !syscalls: change mmap/munmap API to allow setting errno

vm/page-nommu.c, vm/page.c, vm/page.h
slight cleanup, remove commented-out declaration in the header
DONE: RTOS-823
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1055
=> vm: Add static to _page_alloc()

proc/threads.c
This reverts commit 045d6c126f4cc20b919bc5e04edd672b5c560b83.
JIRA: RTOS-818
=> Revert "proc/longjmp: Do reschedule in inf loop"

Makefile
=> Bump version to 3.2.0

hal/armv8m/cpu.c
_cpu_nctx removed in 3d988795143568aa37702978cb198c6914ffec4c
=> armv8m: Fix build

hal/armv7m/arch/exceptions.h, hal/armv7m/exceptions.c, hal/armv7m/imxrt/_init.S, hal/armv7m/stm32/_init.S, proc/process.c, proc/threads.c, proc/threads.h
Expected behaviour (hello causing exception with premeditation):
```
(psh)% sysexec hello
Hello World!!
Exception: 6 #UsageFault
r0=0000000d  r1=00000003  r2=0805037f  r3=00000018
r4=200241f4  r5=00000000  r6=00000001  r7=00000000
r8=00000000  r9=20023648 r10=2000f750 r11=200235ac
r12=00000001 psr=60000000  lr=00000000  pc=00000000
psp=200241d0 msp=20023600 exr=fffffffd bfa=e000ed38
cfs=00020000
Exception: 6 #UsageFault
r0=0000000d  r1=00000003  r2=0805037f  r3=00000018
r4=200241f4  r5=00000000  r6=00000001  r7=00000000
r8=00000000  r9=20023648 r10=2000f750 r11=200235ac
r12=00000001 psr=60000000  lr=00000000  pc=00000000
psp=200241d0 msp=20023600 exr=fffffffd bfa=e000ed38
cfs=00020000
in thread 33, process "hello" (PID: 21)
(psh)%
```
Never ending exception on other targets has been fixed …
=> armv7m: Kill process on exception

proc/process.c
JIRA: RTOS-835
If a signal was to be handled on return from fork syscall and was delivered to the child process, the signal context would be constructed from junk.
This change fixes this issue so that the child can safely handle the signal.
=> proc_fork: copy parent context to child's kstack

hal/armv7m/arch/pmap.h, hal/armv7m/exceptions.c, hal/armv7m/imxrt/10xx/imxrt10xx.c, hal/armv7m/imxrt/10xx/imxrt10xx.h, hal/armv7m/imxrt/_init.S, hal/armv7m/pmap.c, hal/armv7m/stm32/l4/stm32l4.c, hal/armv7m/stm32/stm32.h, hal/pmap.h, hal/sparcv8leon3/pmap-nommu.c, proc/msg-nommu.c, proc/msg.h, proc/process.c, vm/map.c
CI on armv7m targets **will not pass**, as platform configuration became invalid (apps need to be provided with multiple allowed maps, i/o maps are not defined)
=> armv7m: Enable MPU

hal/armv7m/imxrt/117x/config.h
=> imxrt117x: Adapt to changed source of ipg_clk_16M

hal/armv7m/pmap.c
=> armv7m/mpu: Fix kernel not handling multiple regions per map

proc/process.c
Move copying of resources from `process_copy` to `process_vforkThread`.
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1077
JIRA: RTOS-839
=> kernel/proc: Move copying of resources to `process_vforkThread`

hal/armv7m/pmap.c
DONE: RTOS-855
Might fix https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1095
=> armv7m/pmap: Add missing spinlock

hal/sparcv8leon3/gaisler/gr712rc/gr712rc.c, hal/sparcv8leon3/gaisler/gr716/gr716.c, include/arch/sparcv8leon3/gr712rc/gr712rc.h, include/arch/sparcv8leon3/gr716/gr716.h
JIRA: RTOS-847
C99 compliance, forward compatibility with `riscv64`.
=> sparcv8leon3: name union in platformctl_t

hal/riscv64/dtb.c
=> riscv64/dtb: fix condition in dtb_parse

hal/riscv64/cpu.c
=> riscv64: align ustack in hal_cpuCreateContext

hal/armv7a/cpu.c
=> armv7a: align ustack in hal_cpuCreateContext

include/syscalls.h, include/threads.h, include/time.h, log/log.c, posix/posix.c, posix/unix.c, proc/cond.c, proc/cond.h, proc/lock.h, proc/mutex.c, proc/mutex.h, proc/name.c, proc/ports.c, proc/process.c, proc/resource.c, proc/threads.c, syscalls.c, test/vm.c, vm/amap.c, vm/kmalloc.c, vm/map.c, vm/object.c, vm/page-nommu.c, vm/page.c
:exclamation: Kernel API change - intended as non-breaking through wrappers in `libphoenix`.
Implement attributes for mutexes and condvars. Supported attributes behave as in `pthread` library (https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html).
For mutexes - add types:
- `LOCK_TYPE_NORMAL` - no behaviour change (default)
- `LOCK_TYPE_RECURSIVE` - may be locked/unlocked by the same thread recursively
- `LOCK_TYPE_ERRORCHECK` - will return error on recursive lock
For condvars - add clock selection:
- `COND_CLOCK_RELATIVE` - relative timeout, no behaviour change (default)
- `COND_CLOCK_REALTIME` - `utcoffs` + `raw` time used for timeout calculation
- `COND_CLOCK_MONOTONIC` - `raw` time used for timeout calculation
Tests for condvars/mutexes were also …
=> implement mutex/condvar attributes

hal/armv7m/imxrt/timer.c
=> imxrt/timer: Fix interrupt flag clear

proc/process.c
=> process_load (NOMMU): fix phdr size check

hal/armv7a/imx6ull/interrupts.c, hal/armv7a/zynq7000/interrupts.c, hal/armv7m/stm32/interrupts.c, hal/armv8m/Makefile, hal/armv8m/arch/cpu.h, hal/armv8m/cpu.c, hal/armv8m/mcx/Makefile, hal/armv8m/mcx/_init.S, hal/armv8m/mcx/interrupts.c, hal/armv8m/mcx/n94x/Makefile, hal/armv8m/mcx/n94x/config.h, hal/armv8m/mcx/n94x/console.c, hal/armv8m/mcx/n94x/mcxn94x.c, hal/armv8m/mcx/n94x/mcxn94x.h, hal/armv8m/mcx/n94x/timer.c, hal/armv8m/nrf/91/config.h, hal/armv8m/pmap.c, hal/sparcv8leon3/gaisler/irqamp.c, hal/sparcv8leon3/gaisler/irqmp.c, include/arch/armv8m/mcx/n94x/mcxn94x.h, include/arch/armv8m/mcx/syspage.h
JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
https://github.com/phoenix-rtos/libphoenix/pull/371
=> armv8m: Add MCX N94x target, fix armv8m build

hal/sparcv8leon3/gaisler/console.c, hal/sparcv8leon3/gaisler/gr712rc/gr712rc.h, hal/sparcv8leon3/gaisler/gr716/gr716.h, hal/sparcv8leon3/gaisler/timer.c
=> cleanup sparcv8leon3 port

hal/sparcv8leon3/_interrupts-nommu.S, hal/sparcv8leon3/_interrupts.S, hal/sparcv8leon3/_traps.S, hal/sparcv8leon3/gaisler/Makefile, hal/sparcv8leon3/gaisler/generic/Makefile, hal/sparcv8leon3/gaisler/generic/_init.S, hal/sparcv8leon3/gaisler/generic/config.h, hal/sparcv8leon3/gaisler/generic/generic.c, hal/sparcv8leon3/gaisler/generic/generic.h, hal/sparcv8leon3/gaisler/grlib-tn-0018.h, include/arch/sparcv8leon3/generic/generic.h, include/arch/sparcv8leon3/sparcv8leon3.h
=> add sparcv8leon3-generic target

hal/ia32/arch/cpu.h, hal/ia32/console-serial.c, hal/ia32/console.c, hal/ia32/cpu.c, hal/ia32/ia32.h, hal/ia32/init.c, hal/ia32/pci.c
=> hal/ia32: change I/O input parameter to u16

proc/process.c
=> process_load: copy p_filesz bytes instead of p_memsz

vm/map.c
Do not call amap_getanons.
Set offset and lmaxgap.
JIRA: RTOS-895
=> mprotect: fix mapEntrySplit

vm/map.c
DONE: RTOS-928
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1097
=> vm: Increase vm_map pool size

hal/sparcv8leon3/_traps.S
=> hal/sparc: Assume FPU is always present on QEMU

syscalls.c
=> syscalls: make nsleep handle unslept time correctly

hal/sparcv8leon/gaisler/irqamp.c, hal/sparcv8leon/gaisler/irqmp.c, hal/sparcv8leon/gaisler/timer.c
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1228
https://github.com/phoenix-rtos/plo/pull/369
=> hal/sparcv8leon: implement high precision timer

hal/armv7m/imxrt/117x/imxrt117x.c
WDOG1 is a system watchdog, can be enabled at boot via fuses, and can't be disabled once enabled, so it should be a better choice as a global watchdog.
The watchdog can be serviced via `wdgreload` syscall even if kernel was not configured to enable it (e.g. when plo/bootrom enabled the watchdog).
JIRA: JIRA: NIL-658
=> hal/imxrt117x: Use WDOG1 instead of WDOG3

Makefile
=> Bump version to 3.3.0

hal/gaisler/ambapp.c, hal/sparcv8leon/exceptions.c, hal/sparcv8leon/gaisler/Makefile, hal/sparcv8leon/gaisler/console.c, hal/sparcv8leon/gaisler/gaisler.h, hal/sparcv8leon/gaisler/gr740/Makefile, hal/sparcv8leon/gaisler/gr740/_init.S, hal/sparcv8leon/gaisler/gr740/config.h, hal/sparcv8leon/gaisler/gr740/gr740.c, hal/sparcv8leon/gaisler/gr740/gr740.h, hal/sparcv8leon/gaisler/irqamp.c, hal/sparcv8leon/gaisler/l2cache.c, hal/sparcv8leon/gaisler/l2cache.h, hal/sparcv8leon/gaisler/timer.c, hal/sparcv8leon/pmap.c, hal/sparcv8leon/sparcv8leon.h, include/arch/sparcv8leon/gr740/gr740.h, include/arch/sparcv8leon/sparcv8leon.h
JIRA: RTOS-883
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
=> sparcv8leon: implement port for GR740 CPU

posix/posix.c
=> posix/dup2: fix case when fds are the same

hal/armv7a/_interrupts.S, hal/armv7a/exceptions.c, hal/armv7m/imxrt/_init.S, hal/armv7m/stm32/_init.S, hal/armv8m/mcx/_init.S, hal/armv8m/nrf/_init.S, hal/armv8r/_interrupts.S, hal/armv8r/exceptions.c, hal/ia32/_exceptions.S, hal/ia32/_interrupts.S, hal/riscv64/_interrupts.S, hal/riscv64/exceptions.c, hal/sparcv8leon/_traps.S, hal/sparcv8leon/exceptions.c, proc/threads.c, proc/threads.h, syscalls.c
Fixes a return value not being set in child during fork on ARM(7a,8r) and SPARC.
The problem was caused by threads_setupUserValue using current thread stack to obtain context, while in fork we return using parents stack.
JIRA: RTOS-979
=> fork: fix return value not being set in child

posix/unix.c
=> posix/unix: fix typo in unix sockets polling

hal/riscv64/pmap.c
Memory leak was caused by not freeing the level 3 page table when destroying the memory mapping.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1266
=> riscv64/pmap: fix memory leak in pmap_destroy

hal/ia32/Makefile, hal/ia32/console-serial.c, hal/ia32/console-vga.c, hal/ia32/console.c, hal/ia32/console.h
=> ia32/console: support console mirroring

include/syscalls.h, syscalls.c
=> !syscalls: change mprotect to allow setting errno

hal/aarch64/zynqmp/console.c
Added support for routing console UART via PL (programmable logic) subsystem
=> hal: zynqmp console routing via PL

hal/sparcv8leon/_interrupts-nommu.S, hal/sparcv8leon/_interrupts.S, hal/sparcv8leon/_traps.S
JIRA: RTOS-1033
`LEON3_USE_PWR` was changed to `LEON_USE_PWR` in Makefiles when `sparcv8leon3` was renamed to `sparcv8leon`, but wasn't updated in kernel.
=> hal/sparcv8leon: update LEON3_USE_PWR define

hal/armv8m/cpu.c
=> MCXN94x: Log information whether CPU0 or CPU1 is used

hal/armv8m/mcx/n94x/mcxn94x.c, include/arch/armv8m/mcx/n94x/mcxn94x.h
=> hal/mcxn94x: Add platformctl for getting CPU (core) ID

proc/threads.c
=> proc/lock: fix owner NULL dereference

proc/threads.c
Trigger immediate rescheduling when a task reduces its priority. Without this, the task may continue to execute with an effectively higher priority until the next rescheduling event, violating the scheduling policy.
JIRA: DTR-502
=> proc: fix proc_threadPriority

hal/riscv64/arch/cpu.h, hal/riscv64/cpu.c, hal/riscv64/exceptions.c
=> hal/riscv64: fix register name in cpu struct

lib/cbuffer.h
=> cbuffer: fix _cbuffer_discard

proc/process.c
Keep parent's ustack field of thread_t structure after fork and vfork.
JIRA: RTOS-1073
=> proc/process: keep ustack during (v)fork

include/arch/aarch64/types.h, include/arch/armv7a/types.h, include/arch/armv7m/types.h, include/arch/armv7r/types.h, include/arch/armv8m/types.h, include/arch/armv8r/types.h, include/arch/ia32/types.h, include/arch/riscv64/types.h, include/arch/sparcv8leon/types.h, include/types.h, syscalls.c
This change propagates to the user space too
JIRA: RTOS-620
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1261
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1238
=> !hal: make time_t a signed type

hal/riscv64/gaisler/console.c
=> riscv64/gaisler: allow choosing different console UART

include/gaisler/ambapp.h
Add missing vendor id for grspw2_dma core; fix wrong vendor id for grspwrouter core.
=> ambapp.h fix
