- src/posix/posix.c
- src/posix/posix_private.h
Argument to this particular ioctl is a structure with pointer to additional buffer inside. It has to be custom-mapped to msg structure to pass all the data to the receiver.
> ioctl: add custom packing for SIOCGIFCONF ioctl

- src/posix/posix.c
- src/posix/posix.h
- src/proc/process.c
- src/proc/threads.c
Fixed:
- Moving process from children to zombie list was not atomic. Calling waitpid during this transition would incorrectly result in ECHILD.
- Process could be zombified and possibly completely cleaned up by waitpid before all it's threads (protected threads in particular) finished.
- SIGCHLD was sent before process was zombified (calling waitpid could possibly block even after receiving SIGCHLD).
Additionaly, the last thread is now being detached from it's process, while it is destroyed to avoid the need to perform many actions atomically (notifying parent waiting inside waitpid, sending SIGCHLD, zombifying the process and finally destroying the thread).
> Fixed waitpid-related races 

- src/proc/name.c
allow lookup paths not starting with '/'
> proc/name: allow path lookup not starting with '/'

- src/hal/armv7/console-stm32l1.c
- src/hal/armv7/console-stm32l4.c
"\033c" – reset console 
"\033[2J" – clear screen
"\033[20h" – change \r to \r\n
"\033[f" – Set cursor to 0,0
I remove console resetting and changing newline mode which should not be needed.
Now it's aligned to imx6ull console.
@Maxez Please confirm if I wrote correctly :)
> stm32: Do not clean console and change newline mode on start

- src/Makefile.riscv64
As described in the README.md file:
Targets supported currently by the script:
- i386-pc-phoenix
- arm-phoenix
- riscv64-phoenix-elf
Change needed in other repositories.
> Makefile.riscv64: CROSS variable fix

- src/hal/armv7/_init-imxrt.S
When using FPU FPCA bit of CONTROL register should be set.
The assignment (value 0x3) in hal_jmp is incorrect, should
be 0x7. There is defined macro USERCONTROL which assigns
correct value when imxrt is in use.
> armv7m7-imxrt: fix CONTROL register assignment in hal_jmp

- src/hal/arm/spinlock.h
`hal_spinlockClear`
the register `r2` is not used
> arm/spinlock.h: code cleanup

- src/hal/ia32/string.h
`hal_i2s()` - replace `hal_strlen()` and `hal_memcpy()` with simple code
Improved function code 
`hal_memcpy, hal_memset, hal_memsetw., hal_in, hal_out`
is in `plo/efi`.
Question: why is it not used in this kernel?
> hal/ia32/string.h: code optimization

- src/hal/ia32/cpu.c
Instead of three calls `strlen ()`, one and variable.
> hal/ia32/cpu.c: hal_cpuFeatures() - a small change of code

- src/test/vm.c
- src/vm/page.c
Each line displaying pages starts with "vm: " prefix. Pages displayed inside [ ] brackets (same page marker repeated more than 3 times) don't get split between lines.
> vm/page.c: Improved displaying pages

- src/hal/ia32/_init.S
Removed assembler warnings:
```
_init.S:312: Warning: indirect jmp without `*'
_init.S:340: Warning: indirect call without `*'
```
> hal/ia32/_init.S: removed assembler warnings

- src/vm/page.c
After writing a character at column 80 the console automatically moves cursor to the next line, causing pages not to display properly (empty line is added):
This PR fixes the problem.
> ia32/page.c fixed _page_showPages() adding empty lines

- src/main.c
The last argument in argv table is always being
set to NULL. Fixed for NULL to be set after the
arguments.
> syspage: fix parsing syspage progs argsi

- src/hal/ia32/cpu.c
dissassembled code:
```objdump -d cpu.o```
current:
```
00000000 <cpu_getEFLAGS>:
0:   9c                      pushf  
1:   58                      pop    %eax
2:   89 c2                   mov    %eax,%edx
4:   89 d0                   mov    %edx,%eax
6:   c3                      ret    
```
new:
```
00000000 <cpu_getEFLAGS>:
0:   9c                      pushf  
1:   58                      pop    %eax
2:   c3                      ret    
```
current:
``` 
3b4:   8d 04 c5 20 00 00 00    lea    0x20(,%eax,8),%eax
3bb:   89 c0                   mov    %eax,%eax
3bd:   0f 00 d8                ltr    %ax
3c0:   a1 20 00 e0 fe          mov    0xfee00020,%eax
```
new:
```
3b4:   8d 04 c5 20 00 00 00    lea    0x20(,%eax,8),%eax
3bb:   0f 00 d8                ltr    %ax
3be:   a1 20 00 e0 fe …
```
> ia32/cpu.c: small changes in inline asm

- src/hal/arm/cpu.h
- src/hal/armv7/cpu.h
- src/hal/riscv64/cpu.h
Fix issue #108 
I added missing cpu_sendIPI() for targets:
```
arm
armv7
riscv64
```
> added missing cpu_sendIPI()

- src/proc/threads.c
- src/proc/threads.h
Instead of calculating CPU load in a time window using TSC, which
turned out to be buggy on a multiprocessor environment, compute CPU load
as a ratio of task's CPU time and time since a task was created in
kernel's jiffies.
> ia32: Fix CPU load calculation

- src/programs.c
Comparing unsigned int with negative value looks not very good but `programs_a2i()` returns this value.
I don't know if it will be better in this case `continue` or `return -EINVAL`
In addition, the value returned by `programs_decode()` is not checked in `main_initthr()`.
> programs.c: added conversion error check

- src/lib/printf.h
`putch()` does not exists
add `lib_puts()` to `lib/printf.c` and use it instead of `lib_printf()` where there is a string without formatting.
```
int lib_puts(const char *s)
{
hal_consolePrint(ATTR_NORMAL, s);
return 0;
}
```
or in `lib/printf.h`:
```
static inline int lib_puts(const char *s)
{
hal_consolePrint(ATTR_NORMAL, s);
return 0;
}
```
> lib/printf.h: fixed missing lib_putch()

- scripts/mkimg-imxrt.sh
- scripts/mkimg-stm32.sh
Main change: other use of reverse function
- reverse()
- capturing reverse() output
- convert hex string to number
- print the number as a hex string to a file
- reverse()
- redirecting reverse() output to a file
- `$(...)` instead of `` `...` ``
- short help
- `awk` instead of `grep | grep | awk`
- `stat` instead of `du | cut`
- bash extensions (read from here-string, substring)
- variable `i` removed - is not used
In arithmetic expressions `$((...))` you can omit the `$` character.
> mkimg: Other use of reverse function and some code changes

- programs.c
The progssz value should be incremented only if
parsing and allocating is successful
> programs_decode: fix incrementing progssz on error

- hal/arm/Makefile
Current object files ordering causes wrong order of functions inside .init section of kernel elf, due to which imx6ull won't boot correctly.
> arm: Fix object files ordering

- vm/object.c
Fixes error on imx6ull, when .bss section is not initialized with zeros.
> vm: Init kernel object refs counter with 0

- hal/arm/_init-imx6ull.S
- vm/object.c
Since programs are in cpio, copying them in init is obsolete.
> imx6ull: Remove unnecessary programs copying

- proc/threads.c
This should fix the abnormal cpu time rise of `init` process, when another process exits.
> proc: Fix cpu time calculation, if current is NULL

- hal/armv7m/imxrt/117x/console.c
- hal/armv7m/imxrt/117x/imxrt117x.c
- hal/armv7m/imxrt/117x/imxrt117x.h
I corrected name of included file to imxrt117x.
I also removed some compiler warnings.
> imxrt117x: fixed name of included file

- lib/strtoul.c
Now `endptr` points to the last valid character.
> strtoul: endptr changed to the first invalid character

- hal/armv7m/stm32/l4/stm32l4.c
This commit changes the asynchronous division factor so as to achieve the resolution of ~0,5 ms (as seen by RTC's sub-second register).
> stm32l4: Increase the resolution of RTC's sub-second register

- hal/arm/imx6ull.c
There is no such check in  `imxrt117x` i `imxrt10x` .
> imx6ull.c: added missing pointer test

- hal/ia32/pci.c
Fixed PCI enumeration (resetting `d` and `f` indexes). Changed `b`, `d` and `f` indexes type to unsigned int due to `b` index overflow.
> hal/ia32: fixes for PCI enumeration + code cleanup

- include/mman.h
- syscalls.c
- vm/object.c
PR with changes on libphoenix side: [link](https://github.com/phoenix-rtos/libphoenix/pull/74)
> Fixed freeing objects marked as OID_CONTIGUOUS + moved predefined oids from libphoenix

- hal/arm/exceptions.c
- hal/armv7m/exceptions.c
- hal/ia32/exceptions.c
Such corection is in `riscv64`, in the others there is no.
> exceptions.c: added array index corection

- hal/arm/exceptions.c
- hal/armv7m/exceptions.c
- hal/ia32/exceptions.c
- hal/riscv64/exceptions.c
Printing a newline with the bold attribute is probably unnecessary.
In `riscv64` line
```
buff[i++] = '\n';
```
already exists.
> exceptions.c: changed printing new line

- include/posix.h
- posix/posix.c
For now, it seems the only change in kernel needed to support IPv6.
Changes in phoenix-rtos-lwip and libphoenix regarding IPv6 will soon get published.
> posix: Allow creating IPv6 sockets

- hal/armv7m/stm32/l1/stm32l1.c
This version takes less bytes an is faster.
> stm32l1.c: compiler warning removed

- hal/armv7m/imxrt/10xx/imxrt10xx.c
This commit is analogous to https://github.com/phoenix-rtos/plo/pull/26 because of the same procedure.
* The debugger functionality has been checked against to use J-Link (jtag / swd) and [pyOCD](https://github.com/pyocd/pyOCD) (using CMSIS-DAP available on the mimixrt1064-evk board).
* Also a minor update in the comment about clock freq.
> Enable jtag/debuger

- Makefile
Change is supposed to make possible building kernel in serial mode by setting variable explicitly:
TARGET=ia32-generic CONSOLE=serial phoenix-rtos-build/build.sh ...
Referenced by:
https://github.com/phoenix-rtos/plo/pull/25
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/46
> Support for switching to serial mode with variable

- hal/armv7m/imxrt/10xx/imxrt10xx.c
The watchdog initialization is not dependent on plo initialization.
> imxrt: add rtwdog init and refresh

- hal/armv7a/string.h
- hal/armv7m/string.h
Addition to PR #88.
Fix reduces code size if set value is know at compile time ( e.g. `0`, most cases ), compiler will set whole register right away.
I added in `hal_strlen()` `memory` clobber.
> armv7: hal_memset() for memory zeroing has been improved

- hal/armv7m/imxrt/10xx/imxrt10xx.c
- hal/armv7m/imxrt/117x/imxrt117x.c
This fix enables to work the below snippet of code (as example), which is failing (`platformctl`) with `-EINVAL` on imxrt targets without the fix. Additionaly to enable `psh` to act on `reboot` command libphoenix fix is in another PR (https://github.com/phoenix-rtos/libphoenix/pull/82)
```C
platformctl_t pctl = {
.action = pctl_set,
.type = pctl_reboot,
.reboot = {
.magic = PHOENIX_REBOOT_MAGIC
}
};
platformctl(&pctl);  
```
JIRA: RTOS-14
> imxrt: fix platformctl reboot

- syscalls.c
syspageprog_t and syspage_program_t might differ in name's max length.
To protect before memory overwriting, the min size is get.
This change is associated with change of application's name length on imxrt1064:https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/199
In the syscall, wrong size is copied what causes undefined behavior.
JIRA: PD-127
> syscalls/syspageprog: get min name's size in hal_memcpy

- hal/armv7m/stm32/l1/stm32l1.c
- hal/armv7m/stm32/l4/stm32l4.c
- hal/armv7m/stm32/stm32.h
Fixed IRQ setting on STM32 platform
|= was used to change bits in register. = should be used
Identical change has been made on imxrt platfrom
> stm32: Fixed IRQ setting (replaced |= with =)

- include/limits.h
- include/syscalls.h
- posix/posix.c
- posix/posix.h
- posix/posix_private.h
- syscalls.c
JIRA: DTR-12
Implement gethostname/sethostname syscalls.
Required to get hostname command working.
Requires https://github.com/phoenix-rtos/libphoenix/pull/102.
> posix: add gethostname/sethostname syscalls

- hal/ia32/string.h
- hal/riscv64/string.h
- proc/process.c
- proc/threads.c
- proc/threads.h
JIRA: RTOS-63
Add stack cannary (stack overflow detection) for user stack. It consists of 16 bytes water mark on the end of the stack (bottom of the stack). This watermark is checked for corruption on each context switch (only when DEBUG=1). If corruption is detected, system halts and error summary is printed.
Stack overflow is the most common problem during embedded developement. Our system has many threads and this fact forces us to allocate minimal feasable stack size. When new feature is added this often causes stack overflow to occur.
> proc: Added user stack canary

- proc/process.c
- vm/map.c
Currently if exception happens in scheduler - system deadlocks without
any message. Try to output at least some info before taking any
spinlock.
Connected to phoenix-rtos/phoenix-rtos-project#138
Connected to JIRA: RTOS-69
> proc: try to print exception without taking any locks

- hal/armv7m/imxrt/syspage.h
Added syspage_hal_t field at start of syspage_t struct.
Syspage unification.
[JIRA: PD-153](https://jira.phoenix-rtos.com/browse/PD-153)
> hal/syspage: move syspage_hal_t field on top of syspage_t struct

- hal/armv7a/Makefile
Needed memtest for `imx6ull` platform.
JIRA: DTR-85
> armv7a: imx6ull: make memtest compilable again

- proc/process.c
- proc/threads.c
JIRA: RTOS-69
Fixed pmapp != NULL not being checked in scheduler
Was causing a crach when mapp != NULL but pmapp == NULL. Caused by introducing pmapp in the first place
> scheduler: Fixed mapp being used as indicator if pmap is present

- hal/armv7a/exceptions.h
- hal/armv7m/exceptions.h
- hal/ia32/exceptions.h
- hal/riscv64/exceptions.h
- vm/map.c
Previous approach too naive (offending address could be NULL). Changed
to checking exception PC address.
Connected to phoenix-rtos/phoenix-rtos-project#138
Connected to JIRA: RTOS-69
> proc: exceptions: better check for being in kernel

- hal/ia32/console-serial.c
Changed default serial console speed on ia32-generic target to 115200bps.
Fix uart-16550 on real PC hardware.
[JIRA: PD-86](https://jira.phoenix-rtos.com/browse/PD-86)
> hal/ia32/console-serial.c: change default baudrate to 115200bps

- hal/armv7m/imxrt/10xx/imxrt10xx.c
JIRA: RTOS-21
This change enables USB2PLL on imxrt10xx MCUs.
This change is required in order to use USB2 in host mode on imxrt1064.
It was HW tested on imxrt1064.
> hal/imxrt10xx: Enable USB2 PLL

- hal/armv7m/exceptions.c
JIRA: ISC-124
Simple change to move array to static storage.
When trying to build with -Os following error occurs:
```
arm-phoenix-ld: /path/to/project/_build/armv7m4-stm32l4x6/phoenix-rtos-kernel/hal/armv7m/exceptions.o: in function `exceptions_i2s':
/path/to/project/phoenix-rtos-kernel/hal/armv7m/exceptions.c:24: undefined reference to `memcpy'
```
Attempt to use memcpy seems invalid and this change does not fix it, But I think it's better to have this array in .rodata and it removes compilation error.
Only build check
> armv7m: Change table on stack to static const char

- main.c
- proc/process.c
- vm/map.c
- vm/map.h
A change to `proc_syspageSpawnName()` which allows to run syspage programs with the default memory map (dmap) set in plo using the `app` command.
This change additionally solves "a todo", and introduces that the write and read attributes of the selected map are checked before syspage program is launched.
JIRA: RTOS-74
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/80
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/12
> proc: allow sysexec to spawn programs with default map

- hal/armv7a/cpu.h
- hal/armv7m/cpu.c
- hal/armv7m/cpu.h
- hal/armv7m/imxrt/timer.c
- hal/armv7m/stm32/l1/stm32l1.c
- hal/armv7m/stm32/l4/stm32l4.c
- hal/armv7m/stm32/l4/timer.c
- hal/armv7m/stm32/stm32.h
- hal/armv7m/timer.h
- hal/ia32/cpu.h
- hal/riscv64/cpu.h
- proc/threads.c
Based on 32KHz crystal source
Changed wakeup timer API to use microseconds
JIRA: RTOS-79
Use high precision timer for uptime counter
High precision time source is needed by ISC project.
> hal/timer: Implemented high precision timer for STM32L4

- hal/armv7m/imxrt/_init.S
- hal/armv7m/stm32/_init.S
There is only a branch instruction in the `it` block.
I think `it` instruction may be removed.
> armv7m: unnecessary 'it' statements removed

- hal/armv7m/imxrt/_init.S
- initial stack is aligned to 8,
- removed unnecessary label.
JIRA: RTOS-97
Initial stack address depends on **_end** address which might not be aligned to 8.
> hal/imxrt: align initial stack address to 8

- hal/armv7a/imx6ull/_init.S
- hal/armv7a/spinlock.h
In the code alternately has been used strb or strexb, it was wrong approach. Unifed to use only strexb in spinlocks.
After usage of strexb, the status has to be checked. If the operation has failed, it has to be repeated
JIRA: PD-193
System has tendency to hang  on Zynq-7000. It was related to wrong spinlock implementation. The same behaviour can be observed on imx6ull.
> armv7a/spinlock: fix inconsistency in the use of instructions with exclusive access to the memory

- hal/armv7m/imxrt/_init.S
- hal/armv7m/spinlock.h
- hal/armv7m/stm32/_init.S
In the code alternately has been used strb or strexb, it was wrong approach. Unifed to use only strexb in spinlocks.
After usage of strexb, the status has to be checked. If the operation has failed, it has to be repeated
**NOTE: These changes have to be tested on stm32.**
JIRA: RTOS-98
> armv7m/spinlock: inconsistency in the use of instructions with exclusive access to the memory

- syscalls.c
JIRA: RTOS-82
This fixes an error with writing at NULL address, when `handle` argument is equal to NULL.
> syscalls: Fix writing at NULL address in syscall interrupt

- proc/name.c
I moved root directory check before allocating memory for the variable `entry`.
> proc/name.c: fixed memory leak in proc_portRegister()

- include/posix.h
Storage device with 512-byte block size and >256GB of storage capacity couldn't be properly represented with `blkcnt_t` and `blksize_t` types.
[JIRA: RTOS-117](https://jira.phoenix-rtos.com/browse/RTOS-117)
https://github.com/phoenix-rtos/libphoenix/pull/137
> include/posix.h: change blkcnt_t type to long long

- hal/armv7m/imxrt/10xx/console.c
- hal/armv7m/imxrt/117x/console.c
JIRA: RTOS-118
Handle BOARD_CONFIG variables like `UART_CONSOLE=n`, `UARTn_BAUDRATE`
to setup early console based on common to `imxrt-multi` and `plo`
setup.
> imxrt: use UART_CONSOLE to setup early console

- hal/armv7a/imx6ull/_init.S
Remove persistent bit clearing at bootup to be read out later in userspace. Using psh `reboot` or disconnecting power will reset this bit anyway.
JIRA: DTR-181
> armv7a/imx6ull: remove persistent bits clearing in init

- posix/posix.c
Another bad `lookup()` oid usage. `chmod()` `atMode` messages should always be sent to filesystem.
[JIRA: DTR-202](https://jira.phoenix-rtos.com/browse/DTR-202)
> posix/chmod: send atMode messages to filesystem instead of device

- proc/msg.c
JIRA: DTR-3
This fixes memory leak when handling messages processed by kernel threads.
> proc/msg: Unmap memory, when processing kernel messages

- vm/page-nommu.c
- Set `page.mapsz` to `-1` on non-mmu targets.
When calling `vm_pageinfo` on non-mmu targets `page.mapsz` and `page.map` values remain uninitialized. For clarity, `page.map` isn't initialized the suggestion is to set `page.mapsz` to `-1`.
Related to:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/281
> vm: set page mapsz to -1 on non-mmu targets

- include/errno.h
- include/posix.h
- posix/unix.c
Socket receive buffer reallocation is not supported yet.
DONE: DTR-209
> posix/unix: replace SOCK_LARGEBUF flag with SO_RCVBUF option

- include/posix.h
- posix/posix.c
Added `ALLPERMS` and `ACCESSPERMS` macros (the names are taken from BSD: [link](https://github.com/openbsd/src/blob/4cd1828ed9eeebb6486d183eb7e4a99fc9464b70/sys/sys/stat.h#L151-L153))
Cleaned up file type and permission bits macros (removed octal notation in favour of hexedecimal).
Simplified `posix_chmod()` implementation.
Code that manages file permissions should use provided macros instead of 'magic values', e.g. `0777`.
[JIRA: RTOS-148](https://jira.phoenix-rtos.com/browse/RTOS-148)
https://github.com/phoenix-rtos/libphoenix/pull/160
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/59
> Add helper macros for managing file permission bits + simplify chmod() + clean up code

- posix/posix.c
but of a process we don't wait for
JIRA: RTOS-155
Case when there is a zombie, but of a different process than the one we're waiting for wasn't handled at all - caused tight loop in waitpid.
Fixes problem found in waitpid test
> posix/waitpid: Fixed waitpid with WNOHANG when there's a zombie,

- hal/armv7a/imx6ull/Makefile
- hal/armv7a/imx6ull/memtest.c
As the title says, change tab to two spaces. Also do not define short ddr test if `MEMTEST_SHORT` is not defined
> imx6ull: fix indentation in memory test makefile

- proc/process.c
This fixes an Abort exception, when stack canary check is enabled.
JIRA: RTOS-163
This fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/138 on imx6ull.
> process: Set user stack pointer to NULL in execve handler

- posix/posix.c
JIRA: PD-258
- adding check in posix_truncate() for negative _length_
- related issue:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/363
> posix: posix_truncate() check for negative length

- proc/process.c
- proc/threads.c
- proc/threads.h
Process map is changed under threads_common.spinlock to prevent scheduling.
PD-250
> proc: change process map under threads_common.spinlock

- hal/armv7a/_armv7a.S
- hal/armv7a/arch/cpu.h
- hal/armv7a/armv7a.h
- hal/armv7a/pmap.c
Cache management is added to `pmap_enter` and `pmap_remove` to provide data consistency. According to: https://support.xilinx.com/s/article/52035?language=en_US TTL1 and TTL2 entries have to be cleaned and invalidated before update.
Moreover:
1. Barriers have been added to cp15 coprecossor, according to ARM documentation.
2. Added some comments and defines in pmap.
**TODO:**
In current approach TLB is invalidated after each `pmap_switch`, it is unnecessary. ASIDs mechanisms allows to have the same virtual addresses from different processes in TLB. TLB invalidation should be performed in asid alloc/dealloc function when the asids pool is run out.
**CHANGES HAVE NOT BEEN TESTED ON DTR PROJECT**
Executing programs from file system caused abort or prefetch exceptions:
> hal/armv7a: cache management in pmap

- proc/name.c
PD-266
`lookup` for files in `devfs` doesn't work.
> proc/name: allow lookup on paths not starting with '/'

- hal/armv7a/imx6ull/imx6ull.c
Added ENFC clock configuration. Boot ROM sets it to 24 MHz (it has a bug that causes timings specified in TMSpeed field in FCB to not be correctly applied) so that the following description from imx6ull reference manual doesn't really work (I've tested the TMSpeed field in FCB settings and it takes no effect).
[JIRA: DTR-169](https://jira.phoenix-rtos.com/browse/DTR-169)
> hal/armv7a/imx6ull: set ENFC_CLK_ROOT (GPMI NAND root clock) to 198 MHz

- include/sysinfo.h
- vm/map.c
JIRA: ISC-163
Currently there is a problem with estimation of allocated/available memory on NOMMU targets. Shared maps parameters provide adequate information about total system memory.
> vm: Added shared memory maps info to vm_mapinfo

- include/msg.h
JIRA: RTOS-218
Change-Id: I6db713c06ea8e6aee9585eaf721a981e702541ef
This variable is not used anywhere and it results in `type` symbol being defined in multiple object files. We should consider enabling `-fno-common` compilation flag globally (default for gcc >= 10).
> remove global declaration of enum type from msg.h

- hal/armv7a/zynq7000/zynq.c
Software reset is invoked by the `platformctl`.
Current implementation works by accident. The ABI for `zynq7000` is the same as ABI for `imx6ull`. For this reason `reboot` function in [libphoenix-reboot](https://github.com/phoenix-rtos/libphoenix/blob/master/arch/armv7a/reboot.c) works as expected.
**It will be fixed in the next PR.**
PP-63
> hal/armv7a-zynq7000: add software reset

- hal/armv7m/imxrt/117x/imxrt117x.c
- hal/armv7m/imxrt/117x/imxrt117x.h
- include/arch/imxrt1170.h
Required to enable usb-ehci host (otg2) on imxrt1176.
JIRA: NIL-303
> NIL-303: add lpcg platformctls on imxrt117x

- include/syscalls.h
- posix/posix.c
- proc/threads.c
- proc/threads.h
- syscalls.c
Replace usleep with nsleep:
- accept greater time resolution (us -> ns)
- allow returning "unsleept" time
Greater time resolution is needed by `nanosleep()`, returning unsleept time is needed by both `sleep()` and `nanosleep()`.
> Replace usleep with nsleep to allow nanosleep implementation

- include/posix.h
- posix/posix.c
JIRA: RTOS-227
Made struct stat in kernel identical to libphoenix version
Caused fstat to return gibberish
> posix: Fix bad struct stat definition

- hal/riscv64/cpu.c
Fix for user stack pointer value on riscv64
JIRA: RTOS-230
> riscv64: fix user sp value

- hal/armv7a/arch/cpu.h
- hal/armv7m/cpu.c
- hal/armv7m/stm32/l4/stm32l4.c
- hal/ia32/arch/cpu.h
- hal/riscv64/arch/cpu.h
- proc/threads.c
DONE: SKAL-576
Removal of sev, wfe caused MCU insomnia, deep sleep was never achieved. Most likely event flag is stuck high for some reason. All our wakeup sources provide IRQ, so WFI should be good replacement.
> stm32l4: Fix sleep, replace wfe with wfi

- hal/armv7m/stm32/_init.S
DONE: RTOS-246
Fix bug introduced when porting plo to STM32L4. It was working because stack provided by plo was semi-valid.
> stm32: Fix missing MSP set on kernel init

- hal/armv7m/stm32/l4/stm32l4.c
- hal/armv7m/stm32/l4/timer.c
- cmp event could occur before reaching wfi causing wakeup event to be missed and sleep taking much longer (until other wakeup event occured),
- arr event could occur between spinlock set and deep sleep causing timer overflow to be missed (causing ~15 s being lost on system timer).
Remove manual SYSTICK pending flag set, not needed anymore as rescheduling is triggered by timer irqs.
JIRA: ISC-199
> stm32l4: Fix two race conditions in low power

- hal/armv7a/arch/cpu.h
- hal/armv7m/arch/cpu.h
- hal/cpu.h
- hal/ia32/arch/cpu.h
- hal/riscv64/arch/cpu.h
- proc/threads.c
- revert hal code: `hal_cpuSupervisorMode`,
- update hal_cpuSupervisorMode for `Cortex-M`,
- thread in ready queue running in a supervisor mode is always allowed to be selected,
Abort exception occurs when msg is send to the killed thread. 
`msg_send` data are located on stack and shared between threads. If the thread is killed in the middle of message exchange, the abort occurs.
PD--313
> threads_schedule: fix scheduling

- proc/threads.c
- proc/threads.h
- syscalls.c
Fixes bad proc_join approach
- JIRA: RTOS-226
`threadJoin` syscall takes now 2 arguments - timeout and thread id. Existing threadJoin calls which do not specify thread id shall be called with `tid = -1`, which keeps original threadJoin behaviour.
> threads: fix proc_join

- vm/map.c
This causes original elf file residint in the memory to be modified by it's execution. Regresion: forking process with mapped physical memory will cause bad behaviour - pages with physical memory will be copied insted of being shared.
JIRA: RTOS-177
> vm/map: Fix syspage progs being executed in place

- posix/posix.c
- posix: fix setsid() return value and set errno
POSIX compliance:
Upon successful completion, setsid() shall return the value of the new process group ID of the calling process. Otherwise, it shall return -1 and set errno to indicate the error.
> posix: fix setsid() return value

- proc/msg.c
hal_cpuReschedule is clearing spinlock, so additional clear is a bug
DONE: RTOS-313
> msg: Fix extra spinlock clear in proc_respond

- Makefile
- proc/threads.c
DONE: RTOS-310
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/360
> schedule: Allow stack canary enable independent of NDEBUG

- vm/map.c
Fix NULL dereference in sycall for getting map description
Fixed NULL dereference. Probably fixes issue where armv7m4 second flash map was identified as fully used.
> vm/map: Fix NULL dereference in vm_mapinfo

- proc/process.c
PT_GNU_STACK elf section with zero size is used to set non-exec stack.
DONE: RTOS-304
> process: PT_GNU_STACK elf section zero size fix

- hal/armv7m/arch/exceptions.h
- hal/armv7m/exceptions.c
- hal/armv7m/imxrt/_init.S
- hal/armv7m/stm32/_init.S
Move hardware stacked context selection logic from asm to C, add msp and psp value correction.
JIRA: RTOS-311
> armv7m: Fix exception context printout after last changes

- log/log.c
- log/log.h
- proc/threads.c
- syscalls.c
This allows log to be written to in any place, as there are no longer need to take threads_common.spinlock on write. Readers wakeup operation has been moved to:
- after write to klog from user space,
- just before exit from syscall,
- idle thread.
JIRA: RTOS-309
To fix a deadlock on threads_common.spinlock when attempting to use lib_printf from e.g. scheduler.
> klog: Separate log_write from readers wakeup

- .gitignore
- hal/armv7a/cpu.c
- hal/armv7m/cpu.c
- hal/cpu.h
- hal/hal.h
- hal/ia32/arch/cpu.h
- hal/ia32/cpu.c
- hal/riscv64/cpu.c
- proc/elf.h
- proc/process.c
- proc/process.h
- proc/threads.c
- proc/threads.h
- Implements thread local storage on all supported architectures.
JIRA: RTOS-209
> Implement thread local storage

- proc/threads.c
Fixed `ustack` parameter passed in to `hal_cpuCreateContext()`
[JIRA: RTOS-407](https://jira.phoenix-rtos.com/browse/RTOS-407)
> proc/threads.c: fix ustack parameter passed in to hal_cpuCreateContext()

- hal/ia32/_exceptions.S
- hal/ia32/_init.S
- hal/ia32/_interrupts.S
- hal/ia32/arch/cpu.h
- hal/ia32/arch/exceptions.h
- hal/ia32/arch/types.h
- hal/ia32/cpu.c
- hal/ia32/exceptions.c
- hal/ia32/interrupts.c
DONE: RTOS-354
After the change, two and more processes can use the FPU, without the risk of overwriting FPU registers.
> hal/ia32: Enable FPU (with lazy context stacking)

- syscalls.c
There is a problem in msg implementation on MMU targets - it is assumed that the same process does proc_respond and it got the msg from proc_recv. In this case kernel thread did proc_recv and some random user thread does proc_respond, which causes unability to unmap msg related memory in proc_respond. log_scrub is not really needed here, so I chose to fix the problem this way.
DONE: RTOS-434
> syscalls: Remove log_scrub from syscalls_dispatch

- hal/ia32/_interrupts.S
- hal/ia32/arch/cpu.h
- hal/ia32/cpu.c
Existing implementation of stack canary that uses debug registers does not work correctly: value of debug registers is not changed after stack change.
It requires too many changes in API to make it work correctly, so we're removing it.
DONE: RTOS-360
> hal/ia32: Remove stack canary (debug registers)

- hal/ia32/_interrupts.S
- hal/ia32/cpu.c
Functions modifying the stack pointer needs to be implemented in asm, (not as inline asm), this is because the compiler requires the value of the stack pointer to be the same after an asm statement as it was on entry to the statement.
Also listing the stack pointer register `esp` in a clobber list is deprecated now and further will became an error. The previous versions of GCC did not enforce this rule and allowed the stack pointer to appear in the clobber list, with unclear semantics.
Fixes one of the warnings during compilation (https://github.com/phoenix-rtos/phoenix-rtos-project/issues/141):
```
../phoenix-rtos-kernel/hal/ia32/cpu.c:177:2: warning: listing the stack pointer register 'esp' in a clobber list is deprecated [-Wdeprecated]
```
Additional changes along with a detailed …
> ia32: move hal_cpuReschedule() to asm

- hal/riscv64/interrupts.c
Commit 87aca363a3da0f7bd4ffd59723a5fbd375626318 introduced change to how scheduler is invoked, after that change threads scheduler was never invoked. This fix complements that commit. 
Fix: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/740
Fix: https://github.com/phoenix-rtos/phoenix-rtos-doc/issues/152
JIRA: RTOS-513
> interrupts/risc64: fix reschedule invoked indirect

- hal/sparcv8leon3/_interrupts.S
- hal/sparcv8leon3/_traps.S
- hal/sparcv8leon3/arch/cpu.h
- hal/sparcv8leon3/cpu.c
This change:
- fixes wrong psr value being set after interrupt/reschedule
- creates separate cpu context for global/out and local/in registers
- unifies register names in asm code
DONE: JIRA: RTOS-516
> sparcv8leon3: fix interrupts/reschedule

- vm/amap.c
- vm/amap.h
This mattered only on `sizeof(int) != sizeof(void *)` targets (i.e. `riscv64`) Caused silent mapping of .data directly from ELF instead of a private per-process page
DONE: RTOS-514
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/529
> vm/amap: Fix wrong type of offs passed to amap_page

- hal/ia32/_exceptions.S
- hal/ia32/arch/exceptions.h
- hal/ia32/exceptions.c
Debug registers DR4 and DR5 are reserved when debug extensions are
enabled (when the DE flag in control register CR4 is set) and attempts
to reference the DR4 and DR5 registers cause invalid-opcode exceptions
(#UD). When debug extensions are not enabled (the DE flag is clear),
these registers are aliased to debug registers DR6 and DR7
JIRA: RTOS-307
The change is required for the system to work on some hardware.
> hal/ia32: Rename dr4 and dr5 to dr6 and dr7

- hal/armv7a/exceptions.c
- hal/armv7m/exceptions.c
- hal/ia32/exceptions.c
- hal/riscv64/exceptions.c
- hal/sparcv8leon3/exceptions.c
DONE: RTOS-489
We want to reset on exception when not DEBUG
> hal: Fix wrong DEBUG reset on exception logic

- hal/armv7a/imx6ull/_init.S
- hal/armv7a/imx6ull/imx6ull.c
The reason for the removal is that support for the `older iMX6UL` has been replaced by the newer `iMX6ULL`. The code related to the older processor has become dead.
Similarly in [plo/pull/270](https://github.com/phoenix-rtos/plo/pull/270)
JIRA: RTOS-519
> imx6ull: remove dead code

- posix/posix.c
- increase max fd count on STM32 from 8 to 32,
- free ~3840 bytes per process on imxrt* and leon3 targets
DONE: RTOS-522
> posix: Reduce max fd count on all NOMMU targets

- hal/armv7a/cpu.c
- hal/armv7m/cpu.c
- hal/cpu.h
- hal/ia32/cpu.c
- hal/riscv64/_init.S
- hal/riscv64/_interrupts.S
- hal/riscv64/cpu.c
- hal/sparcv8leon3/cpu.c
- proc/threads.c
This PR:
- improves riscv64 asm, removes dead code
- fixes issue with thread-local storage on targets where pointer to tls is set in context
FIXES: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/740
DONE: JIRA: RTOS-514
> riscv64 assembly improvements and thread-local storage fix

- hal/armv7m/imxrt/timer.c
DONE: RTOS-533
Fix analogous to the STM32L4 timer fix - rollover interrupt is triggered just before rollover, not after. That caused race during timer value rollover adjustment
> imxrt/timer: Fix wrong GPT rollover handling during time fetch

- hal/sparcv8leon3/gr716/console.c
- hal/sparcv8leon3/gr716/gr716.c
- hal/sparcv8leon3/gr716/gr716.h
- include/arch/gr716.h
Remove unnecessary gpio configuration when setting IO mux
JIRA: RTOS-535
> gr716: remove unnecessary gpio configuration

- proc/threads.c
Fix race condition while waiting for threads to end - `lastChecked` thread might've been joined by a different thread and no longer belong to `ghosts` list - therefore causing `NULL` dereference.
JIRA: RTOS-542
> proc_join: fix race condition

- proc/threads.c
DONE: RTOS-557
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/624
> proc_threadsList: Fix some thread fields being accessed with the spinlock

- posix/posix.c
- don't allow truncation of read only files,
- don't try to dereference not found file.
DONE: RTOS-558
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/364
> posix: posix_ftruncate bugfix

- hal/ia32/arch/cpu.h
Change removes manual assignment to fixed `edi` register and let compiler (through constraints) decide the best way to store `edx:eax` into `*cb`, this way function inlines very well.
JIRA: RTOS-578
> ia32: optimize rdtsc inline assembly

- lib/printf.c
- lib/printf.h
- vm/page.c
Remove partial printing as lib_printf always adds ANSI color codes.
Breaks testing on zynq sometimes as newline introduced by libklog breaks ANSI codes.
DONE: RTOS-593
RAW output before the change:
RAW output after the change:
> page_showPages: optimize page info printing

- proc/process.c
Fix possible stack corruption on an error path
DONE: RTOS-598
Interrupt may indeed corrupt arguments on the kernel stack on some platforms (e.g. ia32)
Fixes https://github.com/phoenix-rtos/phoenix-rtos-kernel/issues/147
> proc_fork: Disable interrupts before changing kernel stack

- include/msg.h
- lib/Makefile
- lib/idtree.c
- lib/idtree.h
- lib/lib.h
- lib/rb.h
- proc/msg-nommu.c
- proc/msg.c
- proc/msg.h
- proc/ports.c
- proc/ports.h
- syscalls.c
- test/msg.c
- usrv.c
Breaking API change!
Add idtree from libphoenix, some MISRA improvements
JIRA: RTOS-606
> msg: Return a handle instead of kernel pointer in msgRecv

- hal/armv7m/imxrt/10xx/imxrt10xx.c
- hal/armv7m/stm32/l1/stm32l1.c
- hal/armv7m/stm32/l4/stm32l4.c
hal/imxrt10xx: Fix watchdog register name
hal: Enable watchdog independently of NDEBUG
hal: Introduce WATCHDOG_TIMEOUT_MS
Fixes small issues in watchdog, make it indepdent on NDEBUG (see https://github.com/phoenix-rtos/phoenix-rtos-build/pull/163) and introduce configuration WATCHDOG_TIMEOUT_MS as configuration variable for imxrt10xx from board_config.h
Note, that I didn't introduce warning in imx6ull as I'm not sure if it's desired to include board_config.h in init.S
Allow to configure WATCHDOG without BOARD_CONFIG env
Project that uses WATCHDOG variable to specify timeout  need to switch to WATCHDOG_TIMEOUT_MS for that purpose 
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/847
https://github.com/phoenix-rtos/plo/pull/293 …
> Watchdog changes

- hal/armv7a/_interrupts.S
- hal/armv7a/arch/cpu.h
- hal/armv7a/arch/exceptions.h
- hal/armv7a/cpu.c
- hal/armv7a/exceptions.c
- hal/armv7m/arch/cpu.h
- hal/armv7m/cpu.c
- hal/armv7m/imxrt/_init.S
- hal/armv7m/stm32/_init.S
- hal/armv8m/arch/cpu.h
- hal/cpu.h
- hal/ia32/_exceptions.S
- hal/ia32/arch/cpu.h
- hal/ia32/arch/exceptions.h
- hal/ia32/cpu.c
- hal/ia32/exceptions.c
- hal/riscv64/_interrupts.S
- hal/riscv64/arch/cpu.h
- hal/riscv64/cpu.c
- hal/riscv64/exceptions.c
- hal/sparcv8leon3/_interrupts.S
- hal/sparcv8leon3/_traps.S
- hal/sparcv8leon3/arch/cpu.h
- hal/sparcv8leon3/cpu.c
- include/syscalls.h
- proc/threads.c
- proc/threads.h
- syscalls.c
Rework signal handling:
- Signal context is now prepared on user stack
- Return from signal handler is done through new sigreturn syscall
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-kernel/issues/171
JIRA: RTOS-539
> rework signal handling

- log/log.c
After removing BOARD_CONFIG env variable, it became impossible to configure custom kernel log size. Use board_config.h include to re-add this functionality.
JIRA: DTR-3
> log: fix setting custom log size

- hal/armv7a/imx6ull/imx6ull.c
- hal/armv7a/imx6ull/memtest.c
- hal/armv7m/imxrt/10xx/imxrt10xx.c
- hal/armv7m/imxrt/117x/imxrt117x.c
- hal/armv7m/stm32/l1/stm32l1.c
- hal/armv7m/stm32/l4/stm32l4.c
- main.c
- proc/threads.c
- test/proc-fpu.c
- test/proc.c
- test/vm.c
- vm/map.c
The change replaces dead ends like `lib_printf(...); for (;;);` by using `LIB_ASSERT_ALWAYS` in places where there is no chance for klog reader to print an appropriate panic message to the debug console.  This PR additionally checks all uses of `for (;;)` and `while (1)` loops to detect potential missing log-useful information, and normalizes its usage to the MISRA 2012 rules.
Changes are split into separate commits.
> vm/map: replace dead ends with LIB_ASSERT_ALWAYS

- hal/armv7a/arch/types.h
- hal/armv7m/arch/types.h
- hal/armv8m/arch/types.h
- hal/ia32/arch/types.h
- hal/riscv64/arch/types.h
- hal/sparcv8leon3/arch/types.h
- include/mman.h
- include/posix.h
- include/sysinfo.h
- log/log.c
- posix/posix.c
- posix/posix.h
- proc/msg.c
- proc/name.c
- proc/name.h
- proc/process.c
- syscalls.c
- vm/amap.c
- vm/amap.h
- vm/map.c
- vm/map.h
- vm/object.c
- vm/object.h
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306
> mmap: make interface posix compliant

- hal/armv7a/imx6ull/timer.c
- hal/armv7a/zynq7000/timer.c
- hal/armv7m/imxrt/timer.c
- hal/armv7m/stm32/l4/timer.c
- hal/armv8m/nrf/91/timer.c
- hal/ia32/arch/interrupts.h
- hal/ia32/cpu.c
- hal/ia32/hal.c
- hal/ia32/init.c
- hal/ia32/init.h
- hal/ia32/interrupts.c
- hal/ia32/timer.c
- hal/riscv64/timer.c
- hal/sparcv8leon3/gaisler/timer.c
- hal/timer.h
- include/arch/syspage-ia32.h
Add support for 2 timers that may be available in ia32: **Local APIC Timer** and **High Precision Event Timers (HPET)**. If they are available, they will be used instead of old **Programmable Interval Timer (PIT)**.
This change makes it possible to sleep times shorter than 10ms.
> hal/ia32: Implement HP timer

- hal/armv7a/imx6ull/interrupts.c
- hal/armv7a/zynq7000/interrupts.c
Fixes code trying to read from a write-only register.
On both of these platforms interrupt handling code tried to read from EOIR. According to documentation ([link](https://developer.arm.com/documentation/ihi0048/latest/), Table 4-2) EOIR is write-only, reads from it are undefined. The code worked because reads from it probably returned 0.
> hal/zynq7000, hal/imx6ull: Fix accesses to GIC EOIR register

- posix/posix.c
- posix/posix.h
- syscalls.c
Fix behaviour on resulting negative file offset
JIRA: RTOS-397
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/361
tested in https://github.com/phoenix-rtos/phoenix-rtos-project/pull/939
> lseek: Pass resulting offset via a pointer

- hal/armv7a/string.c
- hal/armv7m/string.c
- hal/armv8m/string.c
- hal/ia32/string.c
- hal/ia32/timer.c
- hal/riscv64/string.c
- hal/sparcv8leon3/string.c
- hal/string.h
Fixes bugs reported by @kemonats  here https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/479#issuecomment-1830501494
> hal/ia32: Fix potential buffer overflow in hal_timerFeatures()

- lib/idtree.c
- lib/idtree.h
- vm/map.c
Fixes a problem found in CI with https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/456
New map_entry_t, spawned on entry split during munmap had current proccess assigned to it, instead of the process assiociated with the original entry owner. This caused it to be wrongly unmaped during process end (on vm_mapDestroy).
> vm_munmap: Fix bad entry split on NOMMU

- include/mman.h
- vm/map.c
JIRA: RTOS-738
Munmap changes needed to not produce MAP_FAILED in case of mapping not yet mapped part of memory.
Needed for dynamic linking.
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/507
> mmap: add support for MAP_FIXED

- .codespell_ignore
- hal/riscv64/Makefile
- hal/riscv64/_init.S
- hal/riscv64/_interrupts.S
- hal/riscv64/arch/cpu.h
- hal/riscv64/arch/interrupts.h
- hal/riscv64/arch/pmap.h
- hal/riscv64/arch/spinlock.h
- hal/riscv64/arch/types.h
- hal/riscv64/console.c
- hal/riscv64/cpu.c
- hal/riscv64/dtb.c
- hal/riscv64/exceptions.c
- hal/riscv64/hal.c
- hal/riscv64/interrupts.c
- hal/riscv64/plic.c
- hal/riscv64/plic.h
- hal/riscv64/pmap.c
- hal/riscv64/riscv64.h
- hal/riscv64/sbi.c
- hal/riscv64/sbi.h
- hal/riscv64/spinlock.c
- hal/riscv64/timer.c
- syscalls.c
- Adapt initialization code to booting from PLO
- Reformat code and apply MISRA
- Refactor interrupt handling - properly handle 2 interrupt controllers (CLINT and PLIC), simplify interrupt dispatcher
- Add (partial) support for SBI calls in version 0.2 and higher.
- Modify kernel stack handling: use `hal_cpuKernelStack` variable to store `kstack` value - same approach as on `sparcv8leon3`. Previously `kstack` was set incorrectly, causing exception after `fork`. Variable use here is the most optimal, as when in the future we'll use more cores, `tp` register will have to be reserved in kernel.
> riscv64: boot from PLO

- hal/riscv64/_interrupts.S
- hal/riscv64/arch/cpu.h
Add FPU handling on riscv64.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/988
> riscv64: add FPU context stacking

- proc/threads.c
Plain wakeup was used instead of broadcast - if multiple wake up events have been triggered at once, only one joining thread has been woken up. This could cause some threads executing join() to miss death of it's thread.
Refactored whole queue handling, so wakeupPending is assigned in one place and consistently for all wakeups
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/857
> proc: Fix race condition when multiple thread execute join()

- include/errno.h
- posix/unix.c
Sending message larger than curricular buffer size to DGRAM or SQEPACKET sockets caused infinite block
JIRA: RTOS-778
> posix: fix send() blocking

- include/ioctl.h
- include/msg.h
- log/log.c
- posix/inet.c
- posix/posix.c
- proc/msg-nommu.c
- proc/msg.c
- proc/name.c
- test/msg.c
- usrv.c
**Breaking changes!**
- `oid` is moved from `i.<type>` to common message part
- `const` is added to input data pointer - **this introduces warnings in some functions!**
- `err` is moved from `o.<type>` to `o` struct
- `mtGetAttrAll` msg type is added, allowing the caller to get all file attributes through one message. In this case `struct _attrs` should be allocated and pointer to it should be written into `msg.o.data` (and sizeof to `msg.o.size`). https://github.com/phoenix-rtos/libphoenix/pull/351 provides `_phoenix_initAttrsStruct` that initializes errors in `struct _attrs`.
Convention for the return value is following:
- If the server doesn't at all provide support for `mtGetAttrAll` message, it will return negative value in `msg.o.err` field. Other fields remain uninitialized.
- …
> msg API changes

- proc/process.c
The change adds a check for the existence of a named imap; if a non-existent codeMap (imap) name is provided, an error is reported. If imap name is NULL, codeMap can be NULL, then the default map (imapp = NULL) will be used.
The change fixes a bug related to the psh `sysexec` command, which did not return an error if a non-existent code map was specified.
JIRA: RTOS-810
> process: return error on not existing codeMap

- hal/armv8m/cpu.c
- hal/armv8m/nrf/_init.S
Remove pendsv handler, fix hal_cpuReschedule
JIRA: RTOS-818
> armv8m: Apply changes regarding arch independent longjmp

- hal/armv7m/imxrt/117x/imxrt117x.c
According to reference manual Rev. 1, 05/2021 registers LPSR GPR0-GPR25 do not exist, but in Rev. 2, 06/2023 they do.
JIRA: RTOS-838
> armv7m/imxrt117x: LPSR GPR0-GPR25 exist but are not usable 

- test/vm.c
- vm/page-nommu.c
- vm/page.c
- vm/page.h
- MISRA
- Make `_page_map` and `_page_initSizes` static
- Remove dead function `_page_showSizes`
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1071
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1072
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1073
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1080
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1082
JIRA: RTOS-836
> kernel/vm: Make some functions static and remove dead code

- hal/ia32/arch/cpu.h
Low 16 bits of FPU control word, status word, tag word and Data Pointer Selector are incorrectly placed in the `fpu_context_t` structure.
JIRA: RTOS-842
> kernel/hal/ia32: Fix invalid endianess in FPU context

- hal/armv7m/imxrt/117x/imxrt117x.c
- include/arch/armv7m/imxrt/11xx/imxrt1170.h
JIRA: NIL-441
Shared GPR will be used tp pass some configuration values from M7 to M4.
> armv7m/imxrt117x: add CCM shared GPR registers

- proc/name.c
If server returned off by 1 value, it wasn't detected
and resulted in memcpy with size -1.
JIRA: RTOS-897
> proc_portLookup: fix len check

- posix/unix.c
Sockets can read and write by default. Required for fdopen() to work on unix sockets.
JIRA: RTOS-892
> unix: fix socket flags

- include/errno.h
- lib/cbuffer.c
- lib/cbuffer.h
- posix/unix.c
JIRA: RTOS-877
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/364
> posix: fix unix socket accept/connect, add their nonblocking variants, handle MSG_PEEK in recv

- hal/riscv64/_init.S
- hal/riscv64/pmap.c
- hal/sparcv8leon3/gaisler/generic/_init.S
- hal/sparcv8leon3/gaisler/gr712rc/_init.S
- hal/sparcv8leon3/pmap.c
Before, syspage was copied into a page after kernel end. Now space for syspage is allocated in `.bss` section, which also fixes issues with memory maps definitions in `plo`.
> sparcv8leon3, riscv64: explicitly allocate space for syspage

- hal/riscv64/_interrupts.S
- hal/riscv64/arch/cpu.h
- hal/riscv64/exceptions.c
RISC-V Privileged Architectures V1.10 renamed and generalized sbadaddr to stval. binutils >= 2.43 dropped support for sbadaddr alias.
JIRA: RTOS-913
> riscv: rename sbadaddr to stval

- hal/ia32/ia32.h
Newer binutils versions check closely if asm instructions get operands of correct size.
JIRA: RTOS-912
> hal/ia32: cast operands to correct sizes

- syscalls.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1155
JIRA: RTOS-923
> mmap: allow for not page aligned len

- hal/armv7m/imxrt/10xx/imxrt10xx.c
Remove deinitialization of CCM_ANALOG_PLL_ENET.
ENET module on imxrt106x-evk needs this clock to run.
> hal/imxrt10xx: remove enet PLL deinit

- vm/map.c
JIRA: RTOS-893
Munmap handled badly segments bigger that SIZE_PAGE, after it the rb tree was in corrupted state.
> vm/mman: handle properly munmap of chunks larger than SIZE_PAGE

- include/sysinfo.h
- vm/map.c
Add reporting of map name in `meminfo` syscall.
These features allow implementation of RTT in a more elegant way, with RTT details defined in PLO being passed through to the userspace driver. Using this it is also possible to have console over RTT continuously, using the same buffers, from system start. 
NOTE: This change changes the `meminfo_t` struct used for the `meminfo` syscall. Existing code using this syscall may need to be recompiled.
> !imxrt: Changes related to RTT

- proc/process.c
JIRA: RTOS-912
memsz doesn't matter in that case, caused bug if there was a section with arch data
> proc: do not check sizes in not loadable sections

- hal/riscv64/Makefile
binutils 2.41 silently introduced gp relaxations which for some reason make kernel impossible to build
JIRA: RTOS-912
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/587
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/203/files
> riscv64/Makefile: disable gp relaxations

- hal/ia32/cpu.c
- include/arch/ia32/ia32.h
- include/arch/ia32/syspage.h
plo can now store graphics mode details in syspage (i.e. after setting the mode via VESA VBE) that are then accessible from userspace via platformctl
JIRA: RTOS-906
> ia32: add passing of graphmode params via syspage and platformctl

- hal/arm/Makefile
- hal/arm/rtt.c
- hal/arm/rtt.h
- hal/armv7m/imxrt/10xx/console.c
- hal/armv7m/imxrt/117x/console.c
- lib/helpers.h
UART is enabled by default (current behavior), but can be turned off by defining UART_CONSOLE_KERNEL with an empty value. RTT is enabled by defining RTT_ENABLED with a truthy value and (optionally) selecting a channel to use by RTT_CONSOLE_KERNEL (0-based). UART and RTT may be used at the same time.
RTT driver reuses the control block configured by plo, which must also create a map named via RTT_SYSPAGE_MAP_NAME (default: "rtt"). Channel configuration is not altered at all, so RTT will work even when user-mode driver takes control - exception dumps will still be printed.
JIRA: RTOS-754
> hal/imxrt: Support RTT as a HAL console

- hal/armv7a/zynq7000/zynq.c
- include/arch/armv7a/zynq7000/zynq7000.h
DONE: RTOS-940
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1003
> zynq7000: Fix system reboot on pctl_get on pctl_reboot

- hal/ia32/_exceptions.S
In exception_pushContext the error code was pushed into wrong place on the stack due to offset miscalcution.
In exception_popContext there was one extraoridar pop causing iret to return into instruction at cs not eip.
Some exceptions had been badly marked as having error codes.
JIRA: RTOS-954
> hal/ia32: fix exceptions handling

- vm/map.c
JIRA: RTOS-953
When a memory region with prot read-write got changed to read, then the
memory would not be copied on fork. This result in child and parent
sharing this page that can be changed back to being writeable.
> map: fix mprotected pages not being copied

- hal/armv7m/imxrt/117x/imxrt117x.c
properly set the ranges of gpio pad registers that are controlled differently to the rest
Needed for platformctl to work as intended on iMX RT1170-evk.
related change: https://github.com/phoenix-rtos/plo/pull/364
> hal/imxrt117x: fix IOpad get/set

- hal/ia32/_exceptions.S
While analyzing correctness of `pushContext`, I realized that it can be slightly optimized by using only `eax` instead of both `eax` and `edx`
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/612
> hal/ia32: optimize exception_pushContext

- hal/armv7m/arch/elf.h
- hal/armv8m/arch/elf.h
- hal/armv8r/arch/elf.h
- hal/elf.h
- hal/sparcv8leon3/arch/elf.h
- proc/elf.h
- proc/process.c
> process: unify load on NOMMU

- hal/armv7a/_armv7a.S
- hal/armv7m/imxrt/_init.S
- hal/armv7m/stm32/_init.S
- hal/armv8m/mcx/_init.S
- hal/armv8m/nrf/_init.S
- hal/armv8r/_armv8r.S
JIRA: RTOS-962
In FDPIC format at process startup r7-r9 registers need to store specific value. Thus they must not be used in `hal_jmp`
> hal/arm: optimize register usage

- hal/riscv64/pmap.c
When executing (v)fork, first the memory map is copied and then the new process switches to that map. On risc-v, when mapping new page, cache is invalidated. However, the invalidation may cause page fault when the virtual address is not mapped in the context of currently used memory map. This PR fixes this by switching to the memory map in which the address is mapped, executing the flush/inval and returning to original memory map.
> riscv64/pmap: fix not currently mapped memory being accessed

- hal/armv7m/imxrt/117x/imxrt117x.c
- properly set ranges of registers configured differently
- add a way of setting ODE field in non-LPSR/SNVS GPIO registers
- set proper ranges for setting ODE field in LPSR, SNVS, and remaining GPIO registers
related: https://github.com/phoenix-rtos/plo/pull/367
> hal/imxrt117x: fix IOpad

- proc/process.c
> process/load: fix loading on NOMMU

- hal/ia32/_exceptions.S
- hal/ia32/_interrupts.S
- hal/ia32/interrupts.c
This PR aims to resolve situation with exceptions caused by FPU on Intel.
First commit resolves issue where recently instead of a triple fault on FPU error exception 16 got presented on the screen, due to wrong instruction setting flag.
Second, commit fixes saving context in exceptions.
Third commit changes `fsave` in context saving procedure to `fnsave` to prevent infinite recursion on FPU exception causing a triple fault. Due to this change exception 16 is reported correctly as exception 16 not as tripple fault. Thus, exception 16 is excepted to appear not Triple fault.
Fourth, commit fixes the root cause of the intermittent error. The `cr0Bits` were overwritten by eax during context restoration. We may restore twice from the same context in case of a signal pushed during …
> ia32/exceptions: fix FPU exceptions

- hal/ia32/timer.c
DONE: RTOS-973
Should now work just fine for about 585 years
> ia32/timer: Fix HPET working for only 5 hours

- Makefile
- hal/tlb/tlb.c
> misc: adapt to gcc 14.2

- include/msg.h
- include/posix-statvfs.h
- include/posix-types.h
- include/syscalls.h
- posix/posix.c
- posix/posix.h
- syscalls.c
JIRA: RTOS-965
https://github.com/phoenix-rtos/libphoenix/pull/397
> syscalls: create sys_statvfs syscalls

- hal/armv7m/imxrt/10xx/imxrt10xx.c
Fix `_imxrt_ccmInitEnetPll` to correctly initialize enet PLL.
Enet PLL clk0 is enabled using bit 13 of CCM_ANALOG_PLL_ENET register, but the shift for `enclk0` was  12, which does not match the iMX RT106x RM.
Additionally, bypass was needed during the frequency change.
Related: https://github.com/phoenix-rtos/plo/pull/355
> hal/imxrt106x: fix enet PLL init

- hal/ia32/cpu.c
- hal/ia32/pci.c
- hal/ia32/pci.h
- include/arch/ia32/ia32.h
Setting up EHCI controller on ia32 requires a bit of talking to bios via PCI
JIRA: RTOS-937
`pctl_busmaster` has been removed. Its functionality is realized by `pctl_pcicfg(pci_cfg_busmaster)`
> hal/ia32: Add platformctls for ehci

- hal/riscv64/_interrupts.S
- hal/riscv64/cpu.c
JIRA: RTOS-1038
- Clear FPU CSR when program executes first FPU instruction
- Disable FPU for new threads in `hal_cpuCreateContext`
> riscv64: fix FPU initialization

- hal/aarch64/pmap.c
- hal/armv7a/pmap.c
- hal/armv7m/pmap.c
- hal/armv7r/pmap.c
- hal/armv8m/pmap.c
- hal/armv8r/pmap.c
- hal/ia32/pmap.c
- hal/pmap.h
- hal/riscv64/pmap.c
- hal/sparcv8leon/pmap-nommu.c
- hal/sparcv8leon/pmap.c
- vm/map.c
This change targets performance optimization on multicore targets. Previously, `pmap_remove` had to be called for each page to be removed, which resulted in overhead in TLB shootdowns - one for each page. With this change, a single TLB shootdown can be issued to remove multiple pages, which limits the number of IPIs sent to other cores.
The drawback is that `pmap_common` spinlock is held longer - for the duration of multiple page unmap.
The behaviour on `aarch64` remains unchanged - the flush is done in every loop.
> pmap: allow removing multiple pages in one call

- hal/armv7m/imxrt/10xx/console.c
- hal/armv7m/imxrt/117x/console.c
- hal/armv7m/imxrt/117x/imxrt117x.c
There are some useful warning flags, which are enabled in internal projects, like `-Wundef` and `-Wshadow`.
This commit allow phoenix-rtos-kernel to be build with `-Wundef` without warnings
To enable `-Wundef` flag in the future
> Fix -Wundef warnings with a few macros in imxrt hal

- hal/riscv64/pmap.c
- hal/sparcv8leon/pmap.c
JIRA: RTOS-1069
When `va != NULL`, `pva = &va`. Then `*pva` gets incremented in the loop - and so does `va`. This caused incorrect TLB flush range. Solution is to use the original (aligned) virtual address for all TLB flushes.
> pmap: fix TLB flush address in _pmap_halMapInternal

- proc/process.c
`process_destroy` first destroyed the memory map and then the resources. If an interrupt arrived after `proc_changeMap` to `NULL`, but before handler deregistration, the handler was called with `pmapp = NULL`. This lead to page fault in the handler. Moving the resource destruction before the memory map destruction fixes the issue.
> process_destroy: destroy resources before memory map

- hal/arm/scs.c
- hal/arm/scs.h
- hal/armv8m/stm32/n6/Makefile
- hal/armv8m/stm32/n6/risaf.c
- hal/armv8m/stm32/n6/stm32n6.c
- hal/armv8m/stm32/n6/stm32n6_regs.h
- hal/armv8m/stm32/stm32.h
- include/arch/armv8m/stm32/n6/stm32n6.h
Added `platformctl`s and configuration necessary to implement DMA (cache management, DMA permissions control, RISAF configuration).
Add option to disable the use of HSE oscillator in case it's not available on a given board.
Fix mistakes in functions for RIMC configuration.
Allow DMA to be implemented on STM32N6 and run the system on boards without external oscillator.
> hal/stm32n6: multiple fixes and preparation for DMA

- hal/armv8m/stm32/n6/stm32n6.c
I renamed a member in `platformctl_t` but forgot to rename its uses...
> hal/stm32n6: fix mistake in cache operations

- proc/process.c
- proc/threads.c
- proc/threads.h
Fixes a bug with multithreaded process call an exec leaving other threads running with new process memory map.
Fixes phoenix-rtos/phoenix-rtos-project#1393
JIRA: RTOS-1111
Bug with kernel panic was detected when added alarm thread spawning in forked process to keep alarm working.
> process: terminate threads on exec
